function CreateMerra2ReportHeaderRev1
% This function will create the initial "boilerplate" header info
% for the Merra2 Program
% Written By: Stephen Forczyk
% Created: April 11,2021
% Revised: April 12,2023 added section 1.1 to report
% Revised: April 15,2023 added more tables for the DOI's to the report
%          and the table of figures and table of tables objects
% Revised: July 18-22 2023 added additional tables to report such as
% a list of acronyms used
% Classification: Unclassified
global Datasets ;
global BandDataS MetaDataS;
global LatSpacing LonSpacing RasterAreas;
global RasterLats RasterLons COThighlimit;
global minTauValue PressureLevel42 PressureLevel72;
global PressureLevelUsed framecounter;
global TauCliMeansArray MeansTable MeansTimeTable;
global DataSetLinks;

global Merra2FileName Merra2FileNames MapFormFactor;
global Merra2DataPaths Merra2Path numSelectedFiles;
global Merra2MonthlyMeanDOITable Merra2MonthlyMeanDOIHdrs;
global Merra2HourlyCollection1DOITable Merra2HourlyCollection2DOITable Merra2HourlyDOIHdrs;
global Merra2MonthlyMean3DOITable Merra2Monthly3DOITable Merra2HourlyDOIHdrs;
global Merra2DataSourceTablePt1 Merra2DataSourceTablePt2 Merra2DataSourceHdrs;
global Merra2AppendixHdrs Merra2AppendixTable1 Merra2AppendixTable2;
global Merra2AppendixTable3 Merra2AppendixTable4 Merra2AppendixTable5;
global CountyBoundaryFile;
global CountyBoundaries StateFIPSFile;
global StateFIPSCodes NationalCountiesShp;
global USAStatesShapeFileList USAStatesFileName;
global UrbanAreasShapeFile NorthAmericaLakes FireSummaryFile;
global idebug isavefiles iDemFlag;
global iPrimeRoads iCountyRoads iCommonRoads iStateRecRoads iUSRoads iStateRoads;
global iLakes;
global NumProcFiles ProcFileList;
global RptGenPresent iCreatePDFReport pdffilename rpt chapter tocc lof lot;
global JpegCounter JpegFileList;
global ImageProcessPresent iGOES;
global iReport ifixedImagePaths;
global iSubMean iCheckConfig;
global MonthDayStr MonthDayYearStr YearMonthStr;
global WorldCityFileName World200TopCities;
global iCityPlot maxCities;
global PressureFileName;
global SelectedFiles numSelectedFiles path1;

global fid;
global widd2 lend2;
global initialtimestr igrid ijpeg ilog imovie;
global vert1 hor1 widd lend;
global vert2 hor2 machine;
global chart_time;
global Fz1 Fz2;
global idirector mov izoom iwindow;
global vTemp TempMovieName iMovie;

global matpath datapath;
global jpegpath tiffpath moviepath savepath;
global excelpath ascpath citypath tablepath;
global ipowerpoint PowerPointFile scaling stretching padding;
global ichartnum;
global ColorList RGBVals ColorList2 xkcdVals LandColors;
global orange bubblegum brown brightblue;
% additional paths needed for mapping
global matpath1 mappath matlabpath USshapefilepath;
global northamericalakespath logpath pdfpath govjpegpath;

global shapefilepath Countryshapepath figpath pressurepath averaged1Daypath;
global mappath gridpath countyshapepath nationalshapepath summarypath;
global DayMonthNonLeapYear DayMonthLeapYear CalendarFileName;
global pwd;

%% Build some tables
% Start with the Hourly data but break this up into 2 tables because of the
% length

Merra2HourlyCollection1DOITable=cell(20,3);
Merra2HourlyCollection2DOITable=cell(9,3);
Merra2MonthlyMean3DOITable=cell(26,3);
Merra2HourlyDOIHdrs=cell(1,3);
Merra2HourlyDOIHdrs{1,1}='Descriptive ShortFileName';
Merra2HourlyDOIHdrs{1,2}='Short Name';
Merra2HourlyDOIHdrs{1,3}='DOI Name';
Merra2HourlyCollection1DOITable{1,1}='inst1_2d_asm_Nx';
Merra2HourlyCollection1DOITable{1,2}='M2I1NXASM';
Merra2HourlyCollection1DOITable{1,3}='10.5067/3Z173KIE2TPD';
Merra2HourlyCollection1DOITable{2,1}='inst1_2d_int_Nx';
Merra2HourlyCollection1DOITable{2,2}='M2I1NXINT';
Merra2HourlyCollection1DOITable{2,3}='10.5067/G0U6NGQ3BLE0';
Merra2HourlyCollection1DOITable{3,1}='inst1_2d_lfo_Nx';
Merra2HourlyCollection1DOITable{3,2}='M2I1NXLFO';
Merra2HourlyCollection1DOITable{3,3}='10.5067/RCMZA6TL70BG';
Merra2HourlyCollection1DOITable{4,1}='inst3_3d_asm_Np';
Merra2HourlyCollection1DOITable{4,2}='M2I3NPASM';
Merra2HourlyCollection1DOITable{4,3}='10.5067/QBZ6MG944HW0';
Merra2HourlyCollection1DOITable{5,1}='inst3_3d_aer_Nv';
Merra2HourlyCollection1DOITable{5,2}='M2I3NVAER';
Merra2HourlyCollection1DOITable{5,3}='10.5067/LTVB4GPCOTK2';
Merra2HourlyCollection1DOITable{6,1}='inst3_3d_asm_Nv';
Merra2HourlyCollection1DOITable{6,2}='M2I3NVASM';
Merra2HourlyCollection1DOITable{6,3}='10.5067/WWQSXQ8IVFW8';
Merra2HourlyCollection1DOITable{7,1}='inst3_3d_chm_Nv';
Merra2HourlyCollection1DOITable{7,2}='M2I3NVCHM';
Merra2HourlyCollection1DOITable{7,3}='10.5067/HO9OVZWF3KW2';
Merra2HourlyCollection1DOITable{8,1}='inst3_3d_gas_Nv';
Merra2HourlyCollection1DOITable{8,2}='M2I3NVGAS';
Merra2HourlyCollection1DOITable{8,3}='10.5067/96BUID8HGGX5';
Merra2HourlyCollection1DOITable{9,1}='inst3_2d_gas_Nx';
Merra2HourlyCollection1DOITable{9,2}='M2I3NXGAS';
Merra2HourlyCollection1DOITable{9,3}='10.5067/HNGA0EWW0R09';
Merra2HourlyCollection1DOITable{10,1}='inst6_3d_ana_Np';
Merra2HourlyCollection1DOITable{10,2}='M2I6NPANA';
Merra2HourlyCollection1DOITable{10,3}='10.5067/A7S6XP56VZWS';
Merra2HourlyCollection1DOITable{11,1}='inst6_3d_ana_Nv';
Merra2HourlyCollection1DOITable{11,2}='M2I6NVANA';
Merra2HourlyCollection1DOITable{11,3}='10.5067/IUUF4WB9FT4W';
Merra2HourlyCollection1DOITable{12,1}='statD_2d_slv_Nx';
Merra2HourlyCollection1DOITable{12,2}='M2SDNXSLV';
Merra2HourlyCollection1DOITable{12,3}='10.5067/9SC1VNTWGWV3';
Merra2HourlyCollection1DOITable{13,1}='tavg1_2d_adg_Nx';
Merra2HourlyCollection1DOITable{13,2}='M2T1NXADG';
Merra2HourlyCollection1DOITable{13,3}='10.5067/HM00OHQBHKTP';
Merra2HourlyCollection1DOITable{14,1}='tavg1_2d_aer_Nx';
Merra2HourlyCollection1DOITable{14,2}='M2T1NXAER';
Merra2HourlyCollection1DOITable{14,3}='10.5067/KLICLTZ8EM9D';
Merra2HourlyCollection1DOITable{15,1}='tavg1_2d_chm_Nx';
Merra2HourlyCollection1DOITable{15,2}='M2T1NXCHM';
Merra2HourlyCollection1DOITable{15,3}='10.5067/3RQ5YS674DGQ';
Merra2HourlyCollection1DOITable{16,1}='tavg1_2d_csp_Nx';
Merra2HourlyCollection1DOITable{16,2}='M2T1NXCSP';
Merra2HourlyCollection1DOITable{16,3}='10.5067/H0VVAD8F6MX5';
Merra2HourlyCollection1DOITable{17,1}='tavg1_2d_flx_Nx';
Merra2HourlyCollection1DOITable{17,2}='M2T1NXFLX';
Merra2HourlyCollection1DOITable{17,3}='10.5067/7MCPBJ41Y0K6';
Merra2HourlyCollection1DOITable{18,1}='tavg1_2d_int_Nx';
Merra2HourlyCollection1DOITable{18,2}='M2T1NXINT';
Merra2HourlyCollection1DOITable{18,3}='10.5067/Q5GVUVUIVGO7';
Merra2HourlyCollection1DOITable{19,1}='tavg1_2d_lfo_Nx';
Merra2HourlyCollection1DOITable{19,2}='M2T1NXLFO';
Merra2HourlyCollection1DOITable{19,3}='10.5067/L0T5GEG1NYFA';
Merra2HourlyCollection1DOITable{20,1}='tavg1_2d_lnd_Nx';
Merra2HourlyCollection1DOITable{20,2}='M2T1NXLND';
Merra2HourlyCollection1DOITable{20,3}='10.5067/RKPHT8KC1Y1T';
Merra2HourlyCollection2DOITable{1,1}='tavg1_2d_ocn_Nx';
Merra2HourlyCollection2DOITable{1,2}='M2T1NXOCN';
Merra2HourlyCollection2DOITable{1,3}='10.5067/Y67YQ1L3ZZ4R';
Merra2HourlyCollection2DOITable{2,1}='tavg1_2d_rad_Nx';
Merra2HourlyCollection2DOITable{2,2}='M2T1NXRAD';
Merra2HourlyCollection2DOITable{2,3}='10.5067/Q9QMY5PBNV1T';
Merra2HourlyCollection2DOITable{3,1}='tavg1_2d_slv_Nx';
Merra2HourlyCollection2DOITable{3,2}='M2T1NXSLV';
Merra2HourlyCollection2DOITable{3,3}='10.5067/VJAFPLI1CSIV';
Merra2HourlyCollection2DOITable{4,1}='tavg3_3d_mst_Ne';
Merra2HourlyCollection2DOITable{4,2}='M2T3NEMST';
Merra2HourlyCollection2DOITable{4,3}='10.5067/JRUZ3SJ3ZJ72';
Merra2HourlyCollection2DOITable{5,1}='tavg3_3d_trb_Ne';
Merra2HourlyCollection2DOITable{5,2}='M2T3NETRB';
Merra2HourlyCollection2DOITable{5,3}='10.5067/4I7ZI35QRH8K';
Merra2HourlyCollection2DOITable{6,1}='tavg3_3d_nav_Ne';
Merra2HourlyCollection2DOITable{6,2}='M2T3NENAV';
Merra2HourlyCollection2DOITable{6,3}='10.5067/N5WAKNS1UYQN';
Merra2HourlyCollection2DOITable{7,1}='tavg3_3d_cld_Np';
Merra2HourlyCollection2DOITable{7,2}='M2T3NPCLD';
Merra2HourlyCollection2DOITable{7,3}='10.5067/TX10URJSKT53';
Merra2HourlyCollection2DOITable{8,1}='tavg3_3d_mst_Np';
Merra2HourlyCollection2DOITable{8,2}='M2T3NPMST';
Merra2HourlyCollection2DOITable{8,3}='10.5067/0TUFO90Q2PMS';
Merra2HourlyCollection2DOITable{9,1}='tavg3_3d_rad_Np';
Merra2HourlyCollection2DOITable{9,2}='M2T3NPRAD';
Merra2HourlyCollection2DOITable{9,3}='10.5067/3UGE8WQXZAOK';
Merra2HourlyCollection2DOITable{10,1}='tavg3_3d_tdt_Np';
Merra2HourlyCollection2DOITable{10,2}='M2T3NPTDT';
Merra2HourlyCollection2DOITable{10,3}='10.5067/9NCR9DDDOPFI';
Merra2HourlyCollection2DOITable{11,1}='tavg3_3d_trb_Np';
Merra2HourlyCollection2DOITable{11,2}='M2T3NPTRB';
Merra2HourlyCollection2DOITable{11,3}='10.5067/ZRRJPGWL8AVL';
Merra2HourlyCollection2DOITable{12,1}='tavg3_3d_udt_Np';
Merra2HourlyCollection2DOITable{12,2}='M2T3NPUDT';
Merra2HourlyCollection2DOITable{12,3}='10.5067/CWV0G3PPPWFW';
Merra2HourlyCollection2DOITable{13,1}='tavg3_3d_odt_Np';
Merra2HourlyCollection2DOITable{13,2}='M2T3NPODT';
Merra2HourlyCollection2DOITable{13,3}='10.5067/S0LYTK57786Z';
Merra2HourlyCollection2DOITable{14,1}='tavg3_3d_qdt_Np';
Merra2HourlyCollection2DOITable{14,2}='M2T3NPQDT';
Merra2HourlyCollection2DOITable{14,3}='10.5067/A9KWADY78YHQ';
Merra2HourlyCollection2DOITable{15,1}='tavg3_3d_asm_Nv';
Merra2HourlyCollection2DOITable{15,2}='M2T3NVASM';
Merra2HourlyCollection2DOITable{15,3}='10.5067/SUOQESM06LPK';
Merra2HourlyCollection2DOITable{16,1}='tavg3_3d_cld_Nv';
Merra2HourlyCollection2DOITable{16,2}='M2T3NVCLD';
Merra2HourlyCollection2DOITable{16,3}='10.5067/F9353J0FAHIH';
Merra2HourlyCollection2DOITable{17,1}='tavg3_3d_mst_Nv';
Merra2HourlyCollection2DOITable{17,2}='M2T3NVMST';
Merra2HourlyCollection2DOITable{17,3}='10.5067/ZXTJ28TQR1TR';
Merra2HourlyCollection2DOITable{18,1}='tavg3_3d_rad_Nv';
Merra2HourlyCollection2DOITable{18,2}='M2T3NVRAD';
Merra2HourlyCollection2DOITable{18,3}='10.5067/7GFQKO1T43RW';
Merra2HourlyCollection2DOITable{19,1}='tavg3_2d_glc_Nx';
Merra2HourlyCollection2DOITable{19,2}='M2T3NXGLC';
Merra2HourlyCollection2DOITable{19,3}='10.5067/9ETB4TT5J6US';
% Next create the Monthly Averaged Data Tables
Merra2MonthlyMeanDOITable=cell(28,3);
Merra2MonthlyMeanDOIHdrs=cell(1,3);
Merra2MonthlyMeanDOIHdrs{1,1}='Descriptive ShortFileName';
Merra2MonthlyMeanDOIHdrs{1,2}='Short Name';
Merra2MonthlyMeanDOIHdrs{1,3}='DOI Name';
Merra2MonthlyMeanDOITable{1,1}='instM_2d_asm_Nx';
Merra2MonthlyMeanDOITable{1,2}='M2IMNXASM';
Merra2MonthlyMeanDOITable{1,3}='10.5067/5ESKGQTZG7FO';
Merra2MonthlyMeanDOITable{2,1}='instM_2d_int_Nx';
Merra2MonthlyMeanDOITable{2,2}='M2IMNXINT';
Merra2MonthlyMeanDOITable{2,3}='10.5067/KVTU1A8BWFSJ';
Merra2MonthlyMeanDOITable{3,1}='instM_2d_lfo_Nx';
Merra2MonthlyMeanDOITable{3,2}='M2IMNXLFO';
Merra2MonthlyMeanDOITable{3,3}='10.5067/11F99Y6TXN99';
Merra2MonthlyMeanDOITable{4,1}='instM_2d_gas_Nx';
Merra2MonthlyMeanDOITable{4,2}='M2IMNXGAS';
Merra2MonthlyMeanDOITable{4,3}='10.5067/XOGNBQEPLUC5';
Merra2MonthlyMeanDOITable{5,1}='instM_3d_asm_Np';
Merra2MonthlyMeanDOITable{5,2}='M2IMNPASM';
Merra2MonthlyMeanDOITable{5,3}='10.5067/2E096JV59PK7';
Merra2MonthlyMeanDOITable{6,1}='instM_3d_ana_Np';
Merra2MonthlyMeanDOITable{6,2}='M2IMNPANA';
Merra2MonthlyMeanDOITable{6,3}='10.5067/V92O8XZ30XBI';
Merra2MonthlyMeanDOITable{7,1}='tavgM_2d_adg_Nx';
Merra2MonthlyMeanDOITable{7,2}='M2TMNXADG';
Merra2MonthlyMeanDOITable{7,3}='10.5067/RZIK2TV7PP38';
Merra2MonthlyMeanDOITable{8,1}='tavgM_2d_aer_Nx';
Merra2MonthlyMeanDOITable{8,2}='M2TMNXAER';
Merra2MonthlyMeanDOITable{8,3}='10.5067/FH9A0MLJPC7N';
Merra2MonthlyMeanDOITable{9,1}='tavgM_2d_chm_Nx';
Merra2MonthlyMeanDOITable{9,2}='M2TMNXCHM';
Merra2MonthlyMeanDOITable{9,3}='10.5067/WMT31RKEXK8I';
Merra2MonthlyMeanDOITable{10,1}='tavgM_2d_csp_Nx';
Merra2MonthlyMeanDOITable{10,2}='M2TMNXCSP';
Merra2MonthlyMeanDOITable{10,3}='10.5067/BZPOTGJOQKLU';
Merra2MonthlyMeanDOITable{11,1}='tavgM_2d_flx_Nx';
Merra2MonthlyMeanDOITable{11,2}='M2TMNXFLX';
Merra2MonthlyMeanDOITable{11,3}='10.5067/0JRLVL8YV2Y4';
Merra2MonthlyMeanDOITable{12,1}='tavgM_2d_int_Nx';
Merra2MonthlyMeanDOITable{12,2}='M2TMNXINT';
Merra2MonthlyMeanDOITable{12,3}='10.5067/FQPTQ4OJ22TL';
Merra2MonthlyMeanDOITable{13,1}='tavgM_2d_lfo_Nx';
Merra2MonthlyMeanDOITable{13,2}='M2TMNXLFO';
Merra2MonthlyMeanDOITable{13,3}='10.5067/5V7K6LJD44SY';
Merra2MonthlyMeanDOITable{14,1}='tavgM_2d_lnd_Nx';
Merra2MonthlyMeanDOITable{14,2}='M2TMNXLND';
Merra2MonthlyMeanDOITable{14,3}='10.5067/8S35XF81C28F';
Merra2MonthlyMeanDOITable{15,1}='tavgM_2d_ocn_Nx';
Merra2MonthlyMeanDOITable{15,2}='M2TMNXOCN';
Merra2MonthlyMeanDOITable{15,3}='10.5067/4IASLIDL8EEC';
Merra2MonthlyMeanDOITable{16,1}='tavgM_2d_rad_Nx';
Merra2MonthlyMeanDOITable{16,2}='M2TMNXRAD';
Merra2MonthlyMeanDOITable{16,3}='10.5067/OU3HJDS973O0';
Merra2MonthlyMeanDOITable{17,1}='tavgM_2d_slv_Nx';
Merra2MonthlyMeanDOITable{17,2}='M2TMNXSLV';
Merra2MonthlyMeanDOITable{17,3}='10.5067/AP1B0BA5PD2K';
Merra2MonthlyMeanDOITable{18,1}='tavgM_2d_glc_Nx';
Merra2MonthlyMeanDOITable{18,2}='M2TMNXGLC';
Merra2MonthlyMeanDOITable{18,3}='10.5067/5W8Q3I9WUFGX';
Merra2MonthlyMeanDOITable{19,1}='tavgM_3d_cld_Np';
Merra2MonthlyMeanDOITable{19,2}='M2TMNPCLD';
Merra2MonthlyMeanDOITable{19,3}='10.5067/J9R0LXGH48JR';
Merra2MonthlyMeanDOITable{20,1}='tavgM_3d_mst_Np';
Merra2MonthlyMeanDOITable{20,2}='M2TMNPMST';
Merra2MonthlyMeanDOITable{20,3}='10.5067/ZRZGD0DCK1CG';
Merra2MonthlyMeanDOITable{21,1}='tavgM_3d_rad_Np';
Merra2MonthlyMeanDOITable{21,2}='M2TMNPRAD';
Merra2MonthlyMeanDOITable{21,3}='10.5067/H3YGROBVBGFJ';
Merra2MonthlyMeanDOITable{22,1}='tavgM_3d_tdt_Np';
Merra2MonthlyMeanDOITable{22,2}='M2TMNPTDT';
Merra2MonthlyMeanDOITable{22,3}='10.5067/VILT59HI2MOY';
Merra2MonthlyMeanDOITable{23,1}='tavgM_3d_trb_Np';
Merra2MonthlyMeanDOITable{23,2}='M2TMNPTRB';
Merra2MonthlyMeanDOITable{23,3}='10.5067/2YOIQB5C3ACN';
Merra2MonthlyMeanDOITable{24,1}='tavgM_3d_udt_Np';
Merra2MonthlyMeanDOITable{24,2}='M2TMNPUDT';
Merra2MonthlyMeanDOITable{24,3}='10.5067/YSR6IA5057XX';
Merra2MonthlyMeanDOITable{25,1}='tavgM_3d_odt_Np';
Merra2MonthlyMeanDOITable{25,2}='M2TMNPODT';
Merra2MonthlyMeanDOITable{25,3}='10.5067/Z2KCWAV4GPD2';
Merra2MonthlyMeanDOITable{26,1}='tavgM_3d_qdt_Np';
Merra2MonthlyMeanDOITable{26,2}='M2TMNPQDT';
Merra2MonthlyMeanDOITable{26,3}='10.5067/2ZTU87V69ATP';
Merra2MonthlyMeanDOITable{27,1}='statM_2d_slv_Nx';
Merra2MonthlyMeanDOITable{27,2}='M2SMNXSLV';
Merra2MonthlyMeanDOITable{27,3}='10.5067/KVIMOMCUO83U';
Merra2MonthlyMeanDOITable{28,1}='const_2d_asm_NX';
Merra2MonthlyMeanDOITable{28,2}='M2C0NXASM';
Merra2MonthlyMeanDOITable{28,3}='10.5067/ME5QX6Q5IGGU';
% Finally create the Monthly Mean Diurnal Tables
Merra2MonthlyMean3DOITable{1,1}='instU_2d_asm_Nx';
Merra2MonthlyMean3DOITable{1,2}='M2IUNXASM';
Merra2MonthlyMean3DOITable{1,3}='10.5067/BOJSTZAO2L8R';
Merra2MonthlyMean3DOITable{2,1}='instU_2d_int_Nx';
Merra2MonthlyMean3DOITable{2,2}='M2IUNXINT';
Merra2MonthlyMean3DOITable{2,3}='10.5067/DGAB3HFEYMLY';
Merra2MonthlyMean3DOITable{3,1}='instU_2d_lfo_Nx';
Merra2MonthlyMean3DOITable{3,2}='M2IUNXLFO';
Merra2MonthlyMean3DOITable{3,3}='10.5067/FC3BVJ88Y8A2';
Merra2MonthlyMean3DOITable{4,1}='instU_2d_gas_Nx';
Merra2MonthlyMean3DOITable{4,2}='M2IUNXGAS';
Merra2MonthlyMean3DOITable{4,3}='10.5067/TVJ4MHBED39L';
Merra2MonthlyMean3DOITable{5,1}='instU_3d_asm_Np';
Merra2MonthlyMean3DOITable{5,2}='M2IUNPASM';
Merra2MonthlyMean3DOITable{5,3}='10.5067/6EGRBNEBMIYS';
Merra2MonthlyMean3DOITable{6,1}='instU_3d_ana_Np';
Merra2MonthlyMean3DOITable{6,2}='M2IUNPANA';
Merra2MonthlyMean3DOITable{6,3}='10.5067/TRD91YO9S6E7';
Merra2MonthlyMean3DOITable{7,1}='tavgU_2d_adg_Nx';
Merra2MonthlyMean3DOITable{7,2}='M2TUNXADG';
Merra2MonthlyMean3DOITable{7,3}='10.5067/YZJJXZTFCX6B';
Merra2MonthlyMean3DOITable{8,1}='tavgU_2d_aer_Nx';
Merra2MonthlyMean3DOITable{8,2}='M2TUNXAER';
Merra2MonthlyMean3DOITable{8,3}='10.5067/KPUMVXFEQLA1';
Merra2MonthlyMean3DOITable{9,1}='tavgU_2d_chm_Nx';
Merra2MonthlyMean3DOITable{9,2}='M2TUNXCHM';
Merra2MonthlyMean3DOITable{9,3}='10.5067/5KFZ6GXRHZKN';
Merra2MonthlyMean3DOITable{10,1}='tavgU_2d_csp_Nx';
Merra2MonthlyMean3DOITable{10,2}='M2TUNXCSP';
Merra2MonthlyMean3DOITable{10,3}='10.5067/9PH5QU4CL9E8';
Merra2MonthlyMean3DOITable{11,1}='tavgU_2d_flx_Nx';
Merra2MonthlyMean3DOITable{11,2}='M2TUNXFLX';
Merra2MonthlyMean3DOITable{11,3}='10.5067/LUHPNWAKYIO3';
Merra2MonthlyMean3DOITable{12,1}='tavgU_2d_int_Nx';
Merra2MonthlyMean3DOITable{12,2}='M2TUNXINT';
Merra2MonthlyMean3DOITable{12,3}='10.5067/R2MPVU4EOSWT';
Merra2MonthlyMean3DOITable{13,1}='tavgU_2d_lfo_Nx';
Merra2MonthlyMean3DOITable{13,2}='M2TUNXLFO';
Merra2MonthlyMean3DOITable{13,3}='10.5067/BTSNKAJND3ME';
Merra2MonthlyMean3DOITable{14,1}='tavgU_2d_lnd_Nx';
Merra2MonthlyMean3DOITable{14,2}='M2TUNXLND';
Merra2MonthlyMean3DOITable{14,3}='10.5067/W0J15047CF6N';
Merra2MonthlyMean3DOITable{15,1}='tavgU_2d_ocn_Nx';
Merra2MonthlyMean3DOITable{15,2}='M2TUNXOCN';
Merra2MonthlyMean3DOITable{15,3}='10.5067/KLNAVGAX7J66';
Merra2MonthlyMean3DOITable{16,1}='tavgU_2d_rad_Nx';
Merra2MonthlyMean3DOITable{16,2}='M2TUNXRAD';
Merra2MonthlyMean3DOITable{16,3}='10.5067/4SDCJYK8P9QU';
Merra2MonthlyMean3DOITable{17,1}='tavgU_2d_slv_Nx';
Merra2MonthlyMean3DOITable{17,2}='M2TUNXSLV';
Merra2MonthlyMean3DOITable{17,3}='10.5067/AFOK0TPEVQEK';
Merra2MonthlyMean3DOITable{18,1}='tavgU_2d_glc_Nx';
Merra2MonthlyMean3DOITable{18,2}='M2TUNXGLC';
Merra2MonthlyMean3DOITable{18,3}='10.5067/7VUPQC736SWX';
Merra2MonthlyMean3DOITable{19,1}='tavgU_3d_cld_Np';
Merra2MonthlyMean3DOITable{19,2}='M2TUNPCLD';
Merra2MonthlyMean3DOITable{19,3}='10.5067/EPW7T5UO0C0N';
Merra2MonthlyMean3DOITable{20,1}='tavgU_3d_mst_Np';
Merra2MonthlyMean3DOITable{20,2}='M2TUNPMST';
Merra2MonthlyMean3DOITable{20,3}='10.5067/ZRSN0JU27DK2';
Merra2MonthlyMean3DOITable{21,1}='tavgU_3d_rad_Np';
Merra2MonthlyMean3DOITable{21,2}='M2TUNPRAD';
Merra2MonthlyMean3DOITable{21,3}='10.5067/H140JMDOWB0Y';
Merra2MonthlyMean3DOITable{22,1}='tavgU_3d_tdt_Np';
Merra2MonthlyMean3DOITable{22,2}='M2TUNPTDT';
Merra2MonthlyMean3DOITable{22,3}='10.5067/QPO9E5TPZ8OF';
Merra2MonthlyMean3DOITable{23,1}='tavgU_3d_trb_Np';
Merra2MonthlyMean3DOITable{23,2}='M2TUNPTRB';
Merra2MonthlyMean3DOITable{23,3}='10.5067/2A99C60CG7WC';
Merra2MonthlyMean3DOITable{24,1}='tavgU_3d_udt_Np';
Merra2MonthlyMean3DOITable{24,2}='M2TUNPUDT';
Merra2MonthlyMean3DOITable{24,3}='10.5067/DO715T7T5PG8';
Merra2MonthlyMean3DOITable{25,1}='tavgU_3d_odt_Np';
Merra2MonthlyMean3DOITable{25,2}='M2TUNPODT';
Merra2MonthlyMean3DOITable{25,3}='10.5067/M8OJ09GZP23E';
Merra2MonthlyMean3DOITable{26,1}='tavgU_3d_qdt_Np';
Merra2MonthlyMean3DOITable{26,2}='M2TUNPQDT';
Merra2MonthlyMean3DOITable{26,3}='10.5067/S8HJXIR0BFTS';
Merra2DataSourceHdrs=cell(1,4);
Merra2DataSourceHdrs{1,1}='Data Type';
Merra2DataSourceHdrs{1,2}='Use Dates';
Merra2DataSourceHdrs{1,3}='Source';
Merra2DataSourceHdrs{1,4}='Basing Mode';
Merra2DataSourceTablePt1=cell(21,4);
Merra2DataSourceTablePt2=cell(9,4);
Merra2DataSourceTablePt1{1,1}='Roab pibal dropsonde';
Merra2DataSourceTablePt1{1,2}='Jan 1980-Present';
Merra2DataSourceTablePt1{1,3}='See Rienecker 2011';
Merra2DataSourceTablePt1{1,4}='Conventional';
Merra2DataSourceTablePt1{2,1}='AIREP PIREP ASDAR MDCRS';
Merra2DataSourceTablePt1{2,2}='Jan 1980-Present';
Merra2DataSourceTablePt1{2,3}='NCEP ECMWF JMA';
Merra2DataSourceTablePt1{2,4}='Conventional';
Merra2DataSourceTablePt1{3,1}='POAB';
Merra2DataSourceTablePt1{3,2}='Jan 1980-Aug 2010';
Merra2DataSourceTablePt1{3,3}='BoM';
Merra2DataSourceTablePt1{3,4}='Conventional';
Merra2DataSourceTablePt1{4,1}='Surface Land';
Merra2DataSourceTablePt1{4,2}='Jan 1980-Present';
Merra2DataSourceTablePt1{4,3}='NCEP';
Merra2DataSourceTablePt1{4,4}='Conventional';
Merra2DataSourceTablePt1{5,1}='Surface Ship & Buoy';
Merra2DataSourceTablePt1{5,2}='Jan 1980-Present';
Merra2DataSourceTablePt1{5,3}='ICOADS';
Merra2DataSourceTablePt1{5,4}='Conventional';
Merra2DataSourceTablePt1{6,1}='Wind Profiler';
Merra2DataSourceTablePt1{6,2}='May 1992-Present';
Merra2DataSourceTablePt1{6,3}='UCAR & NCEP';
Merra2DataSourceTablePt1{6,4}='Ground Based Remote Sensed';
Merra2DataSourceTablePt1{7,1}='NEXTRAD VAD Wind';
Merra2DataSourceTablePt1{7,2}='Jun 1997-Present';
Merra2DataSourceTablePt1{7,3}='NCEP';
Merra2DataSourceTablePt1{7,4}='Ground Based Remote Sensed';
Merra2DataSourceTablePt1{8,1}='GMS MTSAT Himawari';
Merra2DataSourceTablePt1{8,2}='Jan 1980-Present';
Merra2DataSourceTablePt1{8,3}='NCEP & JMA';
Merra2DataSourceTablePt1{8,4}='Satellite Derived Wind';
Merra2DataSourceTablePt1{9,1}='Meteosat Atmospheric Motion Vector';
Merra2DataSourceTablePt1{9,2}='Jan 1980-Present';
Merra2DataSourceTablePt1{9,3}='NCEP & EUMETSAT';
Merra2DataSourceTablePt1{9,4}='Satellite Derived Wind';
Merra2DataSourceTablePt1{10,1}='GOES Atmospheric Motion Vector';
Merra2DataSourceTablePt1{10,2}='Jan 1980-Present';
Merra2DataSourceTablePt1{10,3}='NCEP ';
Merra2DataSourceTablePt1{10,4}='Satellite Derived Wind';
Merra2DataSourceTablePt1{11,1}='AVHRR Atmospheric Motion Vector *';
Merra2DataSourceTablePt1{11,2}='Oct 1982-Present';
Merra2DataSourceTablePt1{11,3}='CIMSS';
Merra2DataSourceTablePt1{11,4}='Satellite Derived Wind';
Merra2DataSourceTablePt1{12,1}='SSM/I surface wind speed';
Merra2DataSourceTablePt1{12,2}='Jul 1987-Nov 2009';
Merra2DataSourceTablePt1{12,3}='RSS';
Merra2DataSourceTablePt1{12,4}='Satellite Derived Wind';
Merra2DataSourceTablePt1{13,1}='ERS-1 surface wind vector';
Merra2DataSourceTablePt1{13,2}='Aug 1991-May 1996';
Merra2DataSourceTablePt1{13,3}='ESA';
Merra2DataSourceTablePt1{13,4}='Satellite Derived Wind';
Merra2DataSourceTablePt1{14,1}='ERS-2 surface wind vector';
Merra2DataSourceTablePt1{14,2}='Mar 1996-Mar 2011';
Merra2DataSourceTablePt1{14,3}='ESA';
Merra2DataSourceTablePt1{14,4}='Satellite Derived Wind';
Merra2DataSourceTablePt1{15,1}='QuikSCAT surface wind vector';
Merra2DataSourceTablePt1{15,2}='Jul 1999-Nov 2009';
Merra2DataSourceTablePt1{15,3}='JPL';
Merra2DataSourceTablePt1{15,4}='Satellite Derived Wind';
Merra2DataSourceTablePt1{16,1}='MODIS Atmospheric Motion Vector';
Merra2DataSourceTablePt1{16,2}='Jul 2002-Present';
Merra2DataSourceTablePt1{16,3}='CIMSS & NCEP';
Merra2DataSourceTablePt1{16,4}='Satellite Derived Wind';
Merra2DataSourceTablePt1{17,1}='SSMIS surface wind speed *';
Merra2DataSourceTablePt1{17,2}='Oct 2003-Present';
Merra2DataSourceTablePt1{17,3}='RSS';
Merra2DataSourceTablePt1{17,4}='Satellite Derived Wind';
Merra2DataSourceTablePt1{18,1}='WindSat surface wind vector *';
Merra2DataSourceTablePt1{18,2}='Aug 2007-Aug 2012';
Merra2DataSourceTablePt1{18,3}='NCEP';
Merra2DataSourceTablePt1{18,4}='Satellite Derived Wind';
Merra2DataSourceTablePt1{19,1}='ASCAT surface wind vector *';
Merra2DataSourceTablePt1{19,2}='Sept 2008-Present';
Merra2DataSourceTablePt1{19,3}='NCEP';
Merra2DataSourceTablePt1{19,4}='Satellite Derived Wind';
Merra2DataSourceTablePt1{20,1}='SBUV & SBUV/2 Ozone';
Merra2DataSourceTablePt1{20,2}='Jan 1980-Sept 2004';
Merra2DataSourceTablePt1{20,3}='NASA GES DESC';
Merra2DataSourceTablePt1{20,4}='Satellite Retrieved';
Merra2DataSourceTablePt1{21,1}='SSM/I Rain Rate';
Merra2DataSourceTablePt1{21,2}='Jul 1987-Sept 2009';
Merra2DataSourceTablePt1{21,3}='NASA GES DESC';
Merra2DataSourceTablePt1{21,4}='Satellite Retrieved';
Merra2DataSourceTablePt2{1,1}='TMI Rain Rate';
Merra2DataSourceTablePt2{1,2}='Jan 1998-Apr 2015';
Merra2DataSourceTablePt2{1,3}='NASA GES DESC';
Merra2DataSourceTablePt2{1,4}='Satellite Retrieved';
Merra2DataSourceTablePt2{2,1}='MLS Temperature *';
Merra2DataSourceTablePt2{2,2}='Aug 2004-Present';
Merra2DataSourceTablePt2{2,3}='NASA GES DESC';
Merra2DataSourceTablePt2{2,4}='Satellite Retrieved';
Merra2DataSourceTablePt2{3,1}='MLS Ozone *';
Merra2DataSourceTablePt2{3,2}='Oct 2004-Present';
Merra2DataSourceTablePt2{3,3}='NASA GES DESC';
Merra2DataSourceTablePt2{3,4}='Satellite Retrieved';
Merra2DataSourceTablePt2{4,1}='OMI Total Column Ozone *';
Merra2DataSourceTablePt2{4,2}='Oct 2004-Present';
Merra2DataSourceTablePt2{4,3}='NASA GES DESC';
Merra2DataSourceTablePt2{4,4}='Satellite Retrieved';
Merra2DataSourceTablePt2{5,1}='GSPRO bending angle *';
Merra2DataSourceTablePt2{5,2}='Jul 2004-Present';
Merra2DataSourceTablePt2{5,3}='NCAR & NCEP';
Merra2DataSourceTablePt2{5,4}='Radio Occultation';
Merra2DataSourceTablePt2{6,1}='TOVS';
Merra2DataSourceTablePt2{6,2}='Jan 1980-Oct 2006';
Merra2DataSourceTablePt2{6,3}='NCAR & NESDIS';
Merra2DataSourceTablePt2{6,4}='Satellite Radiance';
Merra2DataSourceTablePt2{7,1}='SSM/I';
Merra2DataSourceTablePt2{7,2}='Jan 1987-Nov 2009';
Merra2DataSourceTablePt2{7,3}='RSS';
Merra2DataSourceTablePt2{7,4}='Satellite Radiance';
Merra2DataSourceTablePt2{8,1}='ATOVS';
Merra2DataSourceTablePt2{8,2}='Jan 1998-Present';
Merra2DataSourceTablePt2{8,3}='NESDIS';
Merra2DataSourceTablePt2{8,4}='Satellite Radiance';
Merra2DataSourceTablePt2{9,1}='GOES (8/10/11/12)';
Merra2DataSourceTablePt2{9,2}='Apr 2001-Mar 2007';
Merra2DataSourceTablePt2{9,3}='NCEP & NESDIS';
Merra2DataSourceTablePt2{9,4}='Satellite Radiance';
Merra2AppendixHdrs=cell(1,2);
Merra2AppendixTable1=cell(20,2);
Merra2AppendixTable2=cell(20,2);
Merra2AppendixTable3=cell(20,2);
Merra2AppendixTable4=cell(20,2);
Merra2AppendixTable5=cell(19,2);
Merra2AppendixHdrs{1,1}='Acronym';
Merra2AppendixHdrs{1,2}='Description';
Merra2AppendixTable1{1,1}='3DVAR';
Merra2AppendixTable1{1,2}='3-D variational data assimilation';
Merra2AppendixTable1{2,1}='4DENVAR';
Merra2AppendixTable1{2,2}='4-D ensemble variational data assimilation';
Merra2AppendixTable1{3,1}='AAOD';
Merra2AppendixTable1{3,2}='Aerosol absorption optical depth';
Merra2AppendixTable1{4,1}='ACARS';
Merra2AppendixTable1{4,2}='Aircraft Comm, Addressing,Report System';
Merra2AppendixTable1{5,1}='AeroCom';
Merra2AppendixTable1{5,2}='Aerosol Comparison Project';
Merra2AppendixTable1{6,1}='AERONET';
Merra2AppendixTable1{6,2}='Aerosol Robotics Network';
Merra2AppendixTable1{7,1}='AIREP';
Merra2AppendixTable1{7,2}='Aircraft report';
Merra2AppendixTable1{8,1}='AIRS';
Merra2AppendixTable1{8,2}='Advanced Infrared Sounder';
Merra2AppendixTable1{9,1}='AMDAR';
Merra2AppendixTable1{9,2}='Aircraft Meteorological Data Relay';
Merra2AppendixTable1{10,1}='AMSR-E';
Merra2AppendixTable1{10,2}='Advanced Microwave Scanning Radiometer for EOS';
Merra2AppendixTable1{11,1}='AMSU-A';
Merra2AppendixTable1{11,2}='Advanced Microwave Sounding Unit A';
Merra2AppendixTable1{12,1}='AMSU-B';
Merra2AppendixTable1{12,2}='Advanced Microwave Sounding Unit B';
Merra2AppendixTable1{13,1}='AOD';
Merra2AppendixTable1{13,2}='Aerosol optical depth';
Merra2AppendixTable1{14,1}='ASCAT';
Merra2AppendixTable1{14,2}='Advanced Scatterometer';
Merra2AppendixTable1{15,1}='ASDAR';
Merra2AppendixTable1{15,2}='Aircraft to Satellite Data Relay';
Merra2AppendixTable1{16,1}='ATMS';
Merra2AppendixTable1{16,2}='Advanced Technology Microwave Sounder';
Merra2AppendixTable1{17,1}='ATOVS';
Merra2AppendixTable1{17,2}='Advanced TIROS Operational Vertical Sounder';
Merra2AppendixTable1{18,1}='AVHRR';
Merra2AppendixTable1{18,2}='Advanced Very High Resolution Radiometer';
Merra2AppendixTable1{19,1}='BoM';
Merra2AppendixTable1{19,2}='Bureau of Meteorology (Australia)';
Merra2AppendixTable1{20,1}='CFSR';
Merra2AppendixTable1{20,2}='Climate Forecast System Reanalysis';
Merra2AppendixTable2{1,1}='CAMS';
Merra2AppendixTable2{1,2}='Climate Forecast System Reanalysis';
Merra2AppendixTable2{2,1}='CMIP';
Merra2AppendixTable2{2,2}='Coupled Model Intercomparison Project';
Merra2AppendixTable2{3,1}='CPC';
Merra2AppendixTable2{3,2}='Climate Prediction Center';
Merra2AppendixTable2{4,1}='CrIS';
Merra2AppendixTable2{4,2}='Cross-Track Infrared Sounder';
Merra2AppendixTable2{5,1}='CRTM';
Merra2AppendixTable2{5,2}='Community Radiative Transfer Model';
Merra2AppendixTable2{6,1}='DRE';
Merra2AppendixTable2{6,2}='Direct radiative effect';
Merra2AppendixTable2{7,1}='ECMWF';
Merra2AppendixTable2{7,2}='European Centre for Medium-Range Weather Forecasts';
Merra2AppendixTable2{8,1}='EOS';
Merra2AppendixTable2{8,2}='Earth Observing System';
Merra2AppendixTable2{9,1}='ERA-20C';
Merra2AppendixTable2{9,2}='ECMWF twentieth century reanalysis';
Merra2AppendixTable2{10,1}='ERA Interim';
Merra2AppendixTable2{10,2}='ECMWF interim reanalysis';
Merra2AppendixTable2{11,1}='ERS';
Merra2AppendixTable2{11,2}='European Remote-Sensing Satellites';
Merra2AppendixTable2{12,1}='FGAT';
Merra2AppendixTable2{12,2}='First guess at appropriate time';
Merra2AppendixTable2{13,1}='GEOS';
Merra2AppendixTable2{13,2}='Goddard Earth Observing System';
Merra2AppendixTable2{14,1}='GES DISC';
Merra2AppendixTable2{14,2}='Goddard Earth Sciences Data Information Services Center';
Merra2AppendixTable2{15,1}='GLATOVS';
Merra2AppendixTable2{15,2}='Goddard Laboratory for Atmospheres TOVS forward model';
Merra2AppendixTable2{16,1}='GMAO';
Merra2AppendixTable2{16,2}='Global Modeling and Assimilation Office';
Merra2AppendixTable2{17,1}='GMS';
Merra2AppendixTable2{17,2}='Geostationary Meteorological Satellite';
Merra2AppendixTable2{18,1}='GOCART';
Merra2AppendixTable2{18,2}='Goddard Chemistry Aerosol Radiation and Transport';
Merra2AppendixTable2{19,1}='GOES';
Merra2AppendixTable2{19,2}='Geostationary Operational Environmental Satellites';
Merra2AppendixTable2{20,1}='GPCP';
Merra2AppendixTable2{20,2}='Global Precipitation Climatology Project';
Merra2AppendixTable3{1,1}='GPSRO';
Merra2AppendixTable3{1,2}='Global positioning system radio occultation';
Merra2AppendixTable3{2,1}='GSI';
Merra2AppendixTable3{2,2}='Gridpoint Statistical Interpolation';
Merra2AppendixTable3{3,1}='GWD';
Merra2AppendixTable3{3,2}='Gravity wave drag';
Merra2AppendixTable3{4,1}='HIRS';
Merra2AppendixTable3{4,2}='High Resolution Infrared Radiation Sounder';
Merra2AppendixTable3{5,1}='IASI';
Merra2AppendixTable3{5,2}='Infrared  Atmospheric  Sounding Interferometer';
Merra2AppendixTable3{6,1}='IAU';
Merra2AppendixTable3{6,2}='Incremental analysis update';
Merra2AppendixTable3{7,1}='IESA';
Merra2AppendixTable3{7,2}='IPCC';
Merra2AppendixTable3{8,1}='JMA';
Merra2AppendixTable3{8,2}='Japan Meteorological Agency';
Merra2AppendixTable3{9,1}='JPSS';
Merra2AppendixTable3{9,2}='Joint Polar Satellite System';
Merra2AppendixTable3{10,1}='JRA-55';
Merra2AppendixTable3{10,2}='Japanese 55-year Reanalysis';
Merra2AppendixTable3{11,1}='MACC';
Merra2AppendixTable3{11,2}='Monitoring Atmospheric Composition and Climate project';
Merra2AppendixTable3{12,1}='MAR';
Merra2AppendixTable3{12,2}='Modèle Atmosphérique Régional';
Merra2AppendixTable3{13,1}='MDCRS';
Merra2AppendixTable3{13,2}='Meteorological Data Collection and Reporting System';
Merra2AppendixTable3{14,1}='MERRA';
Merra2AppendixTable3{14,2}='Modern-Era Retrospective Analysis for Research and Applications';
Merra2AppendixTable3{15,1}='MERRA-2';
Merra2AppendixTable3{15,2}='Modern-Era Retrospective Analysis for Research and Applications, version 2';
Merra2AppendixTable3{16,1}='MetOp';
Merra2AppendixTable3{16,2}='Meteorological Operational Satellites';
Merra2AppendixTable3{17,1}='MHS';
Merra2AppendixTable3{17,2}='Microwave Humidity Sounder';
Merra2AppendixTable3{18,1}='MISR';
Merra2AppendixTable3{18,2}='Multiangle Imaging Spectro Radiometer';
Merra2AppendixTable3{19,1}='MLS';
Merra2AppendixTable3{19,2}='Microwave Limb Sounder';
Merra2AppendixTable3{20,1}='MODIS';
Merra2AppendixTable3{20,2}='Moderate  Resolution  Imaging Spectroradiometer';
Merra2AppendixTable4{1,1}='MSG';
Merra2AppendixTable4{1,2}='Meteosat Second Generation';
Merra2AppendixTable4{2,1}='MSU';
Merra2AppendixTable4{2,2}='Microwave Sounding Unit';
Merra2AppendixTable4{3,1}='MTSAT';
Merra2AppendixTable4{3,2}='Multifunctional Transport Satellite';
Merra2AppendixTable4{4,1}='NAAPS';
Merra2AppendixTable4{4,2}='Navy Aerosol Analysis and Prediction System';
Merra2AppendixTable4{5,1}='NASA';
Merra2AppendixTable4{5,2}='National Aeronautics and Space Administration';
Merra2AppendixTable4{6,1}='NCEP';
Merra2AppendixTable4{6,2}='National Centers for Environmental Prediction';
Merra2AppendixTable4{7,1}='NEXRAD';
Merra2AppendixTable4{7,2}='Next Generation Weather Radar';
Merra2AppendixTable4{8,1}='NMC';
Merra2AppendixTable4{8,2}='National Meteorological Center';
Merra2AppendixTable4{9,1}='NOAA';
Merra2AppendixTable4{9,2}='National Oceanic and Atmospheric Administration';
Merra2AppendixTable4{10,1}='NRL';
Merra2AppendixTable4{10,2}='Naval Research Laboratory';
Merra2AppendixTable4{11,1}='OISST';
Merra2AppendixTable4{11,2}='Optimum Interpolation Sea Surface Temperature';
Merra2AppendixTable4{12,1}='OMI';
Merra2AppendixTable4{12,2}='Ozone Monitoring Instrument';
Merra2AppendixTable4{13,1}='OPAC';
Merra2AppendixTable4{13,2}='Optical Properties of Aerosols and Clouds';
Merra2AppendixTable4{14,1}='OSTIA';
Merra2AppendixTable4{14,2}='Operational Sea Surface Temperature and Sea Ice Analysis';
Merra2AppendixTable4{15,1}='PAOB';
Merra2AppendixTable4{15,2}='Synthetic surface pressure observation';
Merra2AppendixTable4{16,1}='Pibal';
Merra2AppendixTable4{16,2}='Pilot balloon';
Merra2AppendixTable4{17,1}='PIREP';
Merra2AppendixTable4{17,2}='Pilot report';
Merra2AppendixTable4{18,1}='QBO';
Merra2AppendixTable4{18,2}='Quasi-biennial oscillation';
Merra2AppendixTable4{19,1}='Raob';
Merra2AppendixTable4{19,2}='Radiosonde observation';
Merra2AppendixTable4{20,1}='RAS';
Merra2AppendixTable4{20,2}='Relaxed Arakawa–Schubert convection scheme';
Merra2AppendixTable5{1,1}='RMS';
Merra2AppendixTable5{1,2}='Root-mean-square';
Merra2AppendixTable5{2,1}='RSS';
Merra2AppendixTable5{2,2}='Remote Sensing Systems';
Merra2AppendixTable5{3,1}='SBUV';
Merra2AppendixTable5{3,2}='Solar Backscatter Ultraviolet Radiometer';
Merra2AppendixTable5{4,1}='SEVIRI';
Merra2AppendixTable5{4,2}='Spinning Enhanced Visible Infrared Imager';
Merra2AppendixTable5{5,1}='SHEBA';
Merra2AppendixTable5{5,2}='Surface Heat Budget of the Arctic Ocean';
Merra2AppendixTable5{6,1}='SIC';
Merra2AppendixTable5{6,2}='Sea ice concentration';
Merra2AppendixTable5{7,1}='SMAP';
Merra2AppendixTable5{7,2}='Soil Moisture Active Passive satellite';
Merra2AppendixTable5{8,1}='SMOS';
Merra2AppendixTable5{8,2}='Soil Moisture and Ocean Salinity satellite';
Merra2AppendixTable5{9,1}='SNPP';
Merra2AppendixTable5{9,2}='Suomi National Polar-Orbiting Partnership';
Merra2AppendixTable5{10,1}='SSM/I';
Merra2AppendixTable5{10,2}='Special Sensor Microwave Imager';
Merra2AppendixTable5{11,1}='SSMIS';
Merra2AppendixTable5{11,2}='Special Sensor Microwave Imager/Sounder';
Merra2AppendixTable5{12,1}='SST';
Merra2AppendixTable5{12,2}='Sea surface temperature';
Merra2AppendixTable5{13,1}='SSU';
Merra2AppendixTable5{13,2}='Stratospheric Sounding Unit';
Merra2AppendixTable5{14,1}='TIROS';
Merra2AppendixTable5{14,2}='Television Infrared Observation Satellite';
Merra2AppendixTable5{15,1}='TMI';
Merra2AppendixTable5{15,2}='Tropical Rainfall Measuring Mission Microwave Imager';
Merra2AppendixTable5{16,1}='TOA';
Merra2AppendixTable5{16,2}='Top of the atmosphere';
Merra2AppendixTable5{17,1}='TOMS';
Merra2AppendixTable5{17,2}='Total Ozone Mapping Spectrometer';
Merra2AppendixTable5{18,1}='VAD';
Merra2AppendixTable5{18,2}='Velocity Azimuth Display';
Merra2AppendixTable5{19,1}='WMO';
Merra2AppendixTable5{19,2}='World Meteorological Organization';








% Set some flags
JpegCounter=0;
import mlreportgen.dom.*;
import mlreportgen.report.*;
import mlreportgen.utils.*
%% Create the report to include title page and layout
    eval(['cd ' pdfpath(1:length(pdfpath)-1)]);
    rpt = Report(pdffilename,"pdf");
    open(rpt);
    rptstr1=strcat('////PDF file created for this run is-',pdffilename,'.pdf ////');
    fprintf(fid,'%s\n',rptstr1);
    rptstr2=strcat('PDF report can be found at-',pdfpath);
    fprintf(fid,'%s\n',rptstr2);
    rpt.Layout.Landscape = true;
    pageLayoutObj = PDFPageLayout;
    pageLayoutObj.PageSize.Orientation = "landscape";
    pageLayoutObj.PageSize.Height = "8.5in";
    pageLayoutObj.PageSize.Width = "11in";
    pageLayoutObj.PageMargins.Top = "0.5in";
    pageLayoutObj.PageMargins.Bottom = "0.5in";
    pageLayoutObj.PageMargins.Left = "0.5in";
    pageLayoutObj.PageMargins.Right = "0.5in";
    pageLayoutObj.PageMargins.Header = "0.3in";
    pageLayoutObj.PageMargins.Footer = "0.3in";
    add(rpt,pageLayoutObj)
    eval(['cd ' govjpegpath(1:length(govjpegpath)-1)]);
% add a title page
    tp = TitlePage();
    tp.Title = 'Merra-2 Analysis Report';
    tp.Subtitle = 'User Selected Merra-2 Data';
    tp.Image = which('Merra2-LogoA.jpg');
    tp.Author = 'Stephen Forczyk';
    tp.Publisher = 'FRC';
    tp.PubDate = date();
    add(rpt,tp);
% add a table of contents
    tocc = TableOfContents;
    tocc.Title = Text('Table of Contents');
    tocc.Title.Color = 'blue';
    tocc.TOCObj.NumberOfLevels = 2; 
    add(rpt,tocc);
% add a table of figures
lof = ListOfFigures();
append(rpt,lof);
% add  Table of Tables
lot = ListOfTables();
append(rpt,lot);
%% Create Chapter 1 with general program information applicable to all Merra 2 products
    chapter = Chapter("Title", "Merra-2 General Information");
    chapter.Layout.Landscape = true;
    add(chapter,Section('GMAO Reanalysis Products'));
    imdata = imread('GMAO-ReAnalysisProducts.jpg');
    [nhigh,nwid,~]=size(imdata);
    image = mlreportgen.report.FormalImage();
    image.Image = which('GMAO-ReAnalysisProducts.jpg');
    text = Text('GMAO Re-Analysis Product List');
    text.Color = 'red';
    image.Caption = text;
    heightstr=strcat(num2str(nhigh/2),'px');
    widthstr=strcat(num2str(nwid/2),'px');
    image.Height = heightstr;
    image.Width = widthstr;
    image.ScaleToFit=0;
    add(chapter,image); 
    br = PageBreak();
    add(chapter,br);
    parastr1='This section is designed to provide some top-level information on the Merra-2 program.';
    parastr2a='Merra-2 stands for Modern Era Retrospective Analysis For Research and Applications-this being a second version of the effort.'; 
    parastr2b=' This program started in 1980 and is run by the NASA Global Model dnd Assimilation Office (GMAO).';
    parastr2c=' Note that a review the of figure above shows that Merra-2 is one product of several run by GMAO.';
    parastr2d=' At the heart of the program is the Goddard Earth Observing System Model or GOES-5.';
    parastr2e=' The reason for the change from the original Merra program to Merra 2 was to allow for additional data to be ingested by the system';
    parastr2f=' being provided from newer sensors.';
    parastr2g=' Specifically driving the changes was to need to add data from atmospheric sounders and hyperspectral sensors.';
    parastr2h=' The focus of this software package is on the Merra-2 data only.';
    parastr2=strcat(parastr1,parastr2a,parastr2b,parastr2c,parastr2d,parastr2e,parastr2f,parastr2g,parastr2h);
    p1 = Paragraph(parastr2);
    p1.Style = {OuterMargin("0pt", "0pt","50pt","10pt")};
    add(chapter,p1);
    parastr11='GEOS-5 is an integrated series of models that employ a common framework called the Earth System Modelling Framework (ESMF).';
    parastr12=' The acronomy GEOS stands fro Goddard Earth Observering System.';
    parastr13='The GEOS-5 Data Assimilation System integrated the a climate modelling system with a gridpoint system interpolation routine.'; 
    parastr14=' Overall the purpose is to facilitae the development of climate models and predictions.';
    parastr2=strcat(parastr11,parastr12,parastr13,parastr14);
    p2 = Paragraph(parastr2);
    p2.Style = {OuterMargin("0pt", "0pt","50pt","10pt")};
    add(chapter,p2);
% Show actual Earth Image
    eval(['cd ' govjpegpath(1:length(govjpegpath)-1)]);
    imdata = imread('GEOS-5-Actual.jpg');
    [nhigh,nwid,~]=size(imdata);
    image = mlreportgen.report.FormalImage();
    image.Image = which('GEOS-5-Actual.jpg');
    text = Text('Actual GOES Sattelite View');
    text.Color = 'red';
    image.Caption = text;
    heightstr=strcat(num2str(nhigh/2),'px');
    widthstr=strcat(num2str(nwid/2),'px');
    image.Height = heightstr;
    image.Width = widthstr;
    image.ScaleToFit=0;
    add(chapter,image); 
    parastr21='The figure above is actual data taken from one of the GOES satellites on Feb 6,2010.';
    parastr22=' Below this graphic is another chart that was developed using in the GEOS-5 model for the same date and location.';
    parastr23=' There is good agreement between model and observation for at least this view of the cloud cover.'; 
    parastr3=strcat(parastr21,parastr22,parastr23);
    p3 = Paragraph(parastr3);
    p3.Style = {OuterMargin("0pt", "0pt","50pt","10pt")};
    add(chapter,p3);
%   Show model comparison
    eval(['cd ' govjpegpath(1:length(govjpegpath)-1)]);
    imdata = imread('GEOS-5-ModelPred.jpg');
    [nhigh,nwid,~]=size(imdata);
    image = mlreportgen.report.FormalImage();
    image.Image = which('GEOS-5-ModelPred.jpg');
    text = Text('GEOS-5 Model Preedcition Feb 6,2010');
    text.Color = 'red';
    image.Caption = text;
    heightstr=strcat(num2str(nhigh/2),'px');
    widthstr=strcat(num2str(nwid/2),'px');
    image.Height = heightstr;
    image.Width = widthstr;
    image.ScaleToFit=0;
    add(chapter,image); 
 % Show Strengths of Key Strengths Of Merra 2
    add(chapter,br);
    parastr31='The bullet list below indicates some of the key strengths of the Merra 2 reanalysis scheme.';
    parastr32=' This is not intended to be an indepth review of this topic.';
    parastr4=strcat(parastr31,parastr32);
    p4 = Paragraph(parastr4);
    p4.Style = {OuterMargin("0pt", "0pt","50pt","10pt")};
    add(chapter,p4);
    Lists=cell(4,1);
    Lists{1,1}='Significant improvement in precipitation and water vapor climatology over older reanalyses';
    Lists{2,1}='Analysis correction is applied to the forecast model gradually ameliorates precipitation spin-down during early stages of the forecast';
    Lists{3,1}='Provides vertical integrals and analysis increment fields for the closure of atmospheric budgets';
    Lists{4,1}='Incremental Analysis Updates (IAU) to slowly adjust the model states toward the observed state.';
    ul = UnorderedList(Lists);
    add(chapter,ul);
 % Show key limitations
    parastr41='The second list below details key limitations.';
    parastr42=' Interested readers show go to the GMAO website to read detailed reference material.';
    parastr5=strcat(parastr41,parastr42);
    p5 = Paragraph(parastr5);
    p5.Style = {OuterMargin("0pt", "0pt","50pt","10pt")};
    add(chapter,p5); 
    Lists=cell(4,1);
    Lists{1,1}='Changes in the observing system strongly affect trends in many fields (as for other reanalyses);';
    Lists{2,1}='Spatial discontinuity in central African moisture fields associated with rawinsonde input';
    Lists{3,1}='The assimilation routine is “frozen” and will not be updated for newer satellite instruments';
    Lists{4,1}='Quality will eventually degrade as current instruments expire.';
    ul = UnorderedList(Lists);
    add(chapter,ul);
    add(chapter,br);
%% Add a section showing data collection sources available to Merra 2
    add(chapter,Section('Merra-2 Data Sources'));
    parastr501=' One of the biggest changes between Merra 1 and Merra 2 is the addition of new sensor sources.';
    parastr502=' This occurred because additional more modern sensors became available since 1979 and second was the desire to improve the models.';
    parastr503=' The next table provides an overview of the additional sources.';
    parastr509=strcat(parastr501,parastr502,parastr503);
    p51 = Paragraph(parastr509);
    p51.Style = {OuterMargin("0pt", "0pt","20pt","10pt")};
    add(chapter,p51);
    add(chapter,br);
    % Add Part1 of the Merra2 Sources Table
    T100=[Merra2DataSourceHdrs;Merra2DataSourceTablePt1];
    tbl100=Table(T100);
    tbl100.Style = [tbl100.Style {Border('solid','black','3px')}];
    tbl100.TableEntriesHAlign = 'center';
    tbl100.HAlign='center';
    tbl100.ColSep = 'single';
    tbl100.RowSep = 'single';
    r = row(tbl100,1);
    r.Style = [r.Style {Color('red'),Bold(true)}];
    bt100 = BaseTable(tbl100);
    tabletitle = Text('Merra2 Data Sources-Part1');
    tabletitle.Bold = false;
    bt100.Title = tabletitle;
    bt100.TableWidth="7in";
    add(chapter,bt100);
    parastr1001='The table above shows the first 21 data sources that were available for the Merra 2 Program.';
    parastr1002=' Column 1 list the data sources usually as a platform or sensor abbreviation';
    parastr1003=' The dates that these sources contributed are listed in column 2.';
    parastr1004=' Additional source information is provided in the third column.';
    parastr1005=' The class of sensor is indicated in the final column.';
    parastr1006=' Not all the available sensor was assimilated in Merra2 these items are marked with an asterisk in col 1.';
    parastr1007=' A later table lists key acronyms.';
    parastr1009=strcat(parastr1001,parastr1002,parastr1003,parastr1004,parastr1005,parastr1006,parastr1007);
    p1001= Paragraph(parastr1009);
    p1001.Style = {OuterMargin("0pt", "0pt","20pt","10pt")};
    add(chapter,p1001);
    add(chapter,br);
  % Add Part2 of the Merra2 Sources Table
    T101=[Merra2DataSourceHdrs;Merra2DataSourceTablePt2];
    tbl101=Table(T101);
    tbl101.Style = [tbl101.Style {Border('solid','black','3px')}];
    tbl101.TableEntriesHAlign = 'center';
    tbl101.HAlign='center';
    tbl101.ColSep = 'single';
    tbl101.RowSep = 'single';
    r = row(tbl101,1);
    r.Style = [r.Style {Color('red'),Bold(true)}];
    bt101 = BaseTable(tbl101);
    tabletitle = Text('Merra2 Data Sources-Part2');
    tabletitle.Bold = false;
    bt101.Title = tabletitle;
    bt101.TableWidth="7in";
    add(chapter,bt101);
    parastr1101='The table above shows the final 9 data sources that were available for the Merra 2 Program.';
    parastr1102=' Column 1 list the data sources usually as a platform or sensor abbreviation';
    parastr1103=' The dates that these sources contributed are listed in column 2.';
    parastr1104=' Additional source information is provided in the third column.';
    parastr1105=' The class of sensor is indicated in the final column.';
    parastr1106=' A later table lists key acronyms.';
    parastr1109=strcat(parastr1101,parastr1102,parastr1103,parastr1104,parastr1105,parastr1106);
    p1101= Paragraph(parastr1109);
    p1101.Style = {OuterMargin("0pt", "0pt","20pt","10pt")};
    add(chapter,p1101);
    add(chapter,br);
  % Add graphic showing Data observations Merra Vs Merra2
    imdata = imread('MerraVsMerra2Observations.jpg');
    [nhigh,nwid,~]=size(imdata);
    image = mlreportgen.report.FormalImage();
    image.Image = which('MerraVsMerra2Observations.jpg');
    text = Text('Merra2 Data Returned Compared To Merra');
    text.Color = 'red';
    image.Caption = text;
    heightstr=strcat(num2str(nhigh/2),'px');
    widthstr=strcat(num2str(nwid/2),'px');
    image.Height = heightstr;
    image.Width = widthstr;
    image.ScaleToFit=0;
    add(chapter,image); 
    parastr81='The purpose in showing this chart is to just provide a quicklook at how the observations increased with Merra2.';
    parastr82=' In this case the Figure of Merit is the number of observations assimilated per 6 hour time period.';
    parastr89=strcat(parastr81,parastr82);
    p8 = Paragraph(parastr89);
    p8.Style = {OuterMargin("0pt", "0pt","10pt","10pt")};
    add(chapter,p8);
    add(chapter,br);

  % Add paragraph on Data assimilation process
    parastr1201='Data assimilation is a very complex process.';
    parastr1202=' Basically the term refers to pulling data from one or more sources to feed a climate model.';
    parastr1203=' In the case of the Merra2 program this model referred to is the GOES-5.';
    parastr1204=' This model is the Goddard Earth Observing System model version 5 and in this system the atmosphere has 72 different pressure level.';
    parastr1205=' The goal is to model the earth atmosphere to enable weather prediction and climate changes.';
    parastr1206=' GOES-5 has many models and the assimulation can be single level to many levels.';
    parastr1207=' Details will be provided for specific products-for Atmospheric Aerosols a single level assimilation technique is used.';
    parastr1208=' Single level means that the the model will used gridded data inputs for a single pressure level to make model predictions.';
    parastr1209=strcat(parastr1201,parastr1202,parastr1203,parastr1204,parastr1205,parastr1206,parastr1207,parastr1208);
    p1201= Paragraph(parastr1209);
    p1201.Style = {OuterMargin("0pt", "0pt","20pt","10pt")};
    add(chapter,br);
    %% Add Acronym Table-Part 1
    T102=[Merra2AppendixHdrs;Merra2AppendixTable1];
    tbl102=Table(T102);
    tbl102.Style = [tbl102.Style {Border('solid','black','3px')}];
    tbl102.TableEntriesHAlign = 'center';
    tbl102.HAlign='center';
    tbl102.ColSep = 'single';
    tbl102.RowSep = 'single';
    r = row(tbl102,1);
    r.Style = [r.Style {Color('red'),Bold(true)}];
    bt102 = BaseTable(tbl102);
    tabletitle = Text('Merra2 Acronym List Part 1');
    tabletitle.Bold = false;
    bt102.Title = tabletitle;
    bt102.TableWidth="7in";
    add(chapter,bt102);
    parastr1301='The table above shows Part 1 of the list of commonly used acronyms used in Merra 2.';
    parastr1302=' Refer to this table to fill in the details from the two previous Merra2 sources table.';
    parastr1309=strcat(parastr1301,parastr1302);
    p39= Paragraph(parastr1309);
    p39.Style = {OuterMargin("0pt", "0pt","20pt","10pt")};
    add(chapter,p39);
    add(chapter,br);
   %% Add Acronym Table-Part 2
    T103=[Merra2AppendixHdrs;Merra2AppendixTable2];
    tbl103=Table(T103);
    tbl103.Style = [tbl103.Style {Border('solid','black','3px')}];
    tbl103.TableEntriesHAlign = 'center';
    tbl103.HAlign='center';
    tbl103.ColSep = 'single';
    tbl103.RowSep = 'single';
    r = row(tbl103,1);
    r.Style = [r.Style {Color('red'),Bold(true)}];
    bt103 = BaseTable(tbl103);
    tabletitle = Text('Merra2 Acronym List Part 2');
    tabletitle.Bold = false;
    bt103.Title = tabletitle;
    bt103.TableWidth="7in";
    add(chapter,bt103);
    parastr1401='This is Part 2 of the table showing a list of commonly used acronyms used in Merra 2.';
    parastr1402=' Refer to this table to fill in the details from the two previous Merra2 sources table.';
    parastr1409=strcat(parastr1401,parastr1402);
    p49= Paragraph(parastr1409);
    p49.Style = {OuterMargin("0pt", "0pt","20pt","10pt")};
    add(chapter,p49);
    add(chapter,br);
   %% Add Acronym Table-Part 3
    T104=[Merra2AppendixHdrs;Merra2AppendixTable3];
    tbl104=Table(T104);
    tbl104.Style = [tbl104.Style {Border('solid','black','3px')}];
    tbl104.TableEntriesHAlign = 'center';
    tbl104.HAlign='center';
    tbl104.ColSep = 'single';
    tbl104.RowSep = 'single';
    r = row(tbl104,1);
    r.Style = [r.Style {Color('red'),Bold(true)}];
    bt104 = BaseTable(tbl104);
    tabletitle = Text('Merra2 Acronym List Part 3');
    tabletitle.Bold = false;
    bt104.Title = tabletitle;
    bt104.TableWidth="7in";
    add(chapter,bt104);
    parastr1501='This is Part 3 of the table showing a list of commonly used acronyms used in Merra 2.';
    parastr1502=' Refer to this table to fill in the details from the two previous Merra2 sources table.';
    parastr1509=strcat(parastr1501,parastr1502);
    p59= Paragraph(parastr1509);
    p59.Style = {OuterMargin("0pt", "0pt","20pt","10pt")};
    add(chapter,p59);
    add(chapter,br);
   %% Add Acronym Table-Part 4
    T105=[Merra2AppendixHdrs;Merra2AppendixTable4];
    tbl105=Table(T105);
    tbl105.Style = [tbl105.Style {Border('solid','black','3px')}];
    tbl105.TableEntriesHAlign = 'center';
    tbl105.HAlign='center';
    tbl105.ColSep = 'single';
    tbl105.RowSep = 'single';
    r = row(tbl105,1);
    r.Style = [r.Style {Color('red'),Bold(true)}];
    bt105 = BaseTable(tbl105);
    tabletitle = Text('Merra2 Acronym List Part 4');
    tabletitle.Bold = false;
    bt105.Title = tabletitle;
    bt105.TableWidth="7in";
    add(chapter,bt105);
    parastr1601='This is Part 4 of the table showing a list of commonly used acronyms used in Merra 2.';
    parastr1602=' Refer to this table to fill in the details from the two previous Merra2 sources table.';
    parastr1609=strcat(parastr1601,parastr1602);
    p69= Paragraph(parastr1609);
    p69.Style = {OuterMargin("0pt", "0pt","20pt","10pt")};
    add(chapter,p69);
    add(chapter,br);
   %% Add Acronym Table-Part 5
    T106=[Merra2AppendixHdrs;Merra2AppendixTable5];
    tbl106=Table(T106);
    tbl106.Style = [tbl106.Style {Border('solid','black','3px')}];
    tbl106.TableEntriesHAlign = 'center';
    tbl106.HAlign='center';
    tbl106.ColSep = 'single';
    tbl106.RowSep = 'single';
    r = row(tbl106,1);
    r.Style = [r.Style {Color('red'),Bold(true)}];
    bt106 = BaseTable(tbl106);
    tabletitle = Text('Merra2 Acronym List Part 5');
    tabletitle.Bold = false;
    bt106.Title = tabletitle;
    bt106.TableWidth="7in";
    add(chapter,bt106);
    parastr1701='This is Part 5 of the table showing a list of commonly used acronyms used in Merra 2.';
    parastr1702=' Refer to this table to fill in the details from the two previous Merra2 sources table.';
    parastr1709=strcat(parastr1701,parastr1702);
    p79= Paragraph(parastr1709);
    p79.Style = {OuterMargin("0pt", "0pt","20pt","10pt")};
    add(chapter,p79);
    add(chapter,br);

%% Add another section to Chapter 1
    add(chapter,Section('Merra-2 File Formats'));
    parastr51='This next section will provide information that is applicable to all Merra-2 datasets and should be understood by the reader.';
    parastr52=' One signficant change for the Merra 2 information is that the files are written in netCDF format.';
    parastr53=' Previous Merra data was in HDF format. This is npt really a big change because netCDF format is dervived from HDF format.'; 
    parastr54=' Typically the same software can read both formats since they are closely related.';
    parastr55=' Merra-2 archive files can be quite large so some data compression and interpolations schemes have been used.';
    parastr56=' The files have been compressed using a GRIB technique which is a lossy method but care was taken that this process did not degrade the data.';
    parastr57=' Merra 2 data assimilation takes place on a cube square grid however during processing 2D datasets are interpolated to a fixed grid.';
    parastr58=' In a few cases bilinear interpolation was used to set the data values on the grid but in most cases a simple binning procedure was used.';
    parastr59=' Most datasets are really 3 d with lat/lon spatial diemnsions and a separate time dimension.';
    parastr6=strcat(parastr51,parastr52,parastr53,parastr54,parastr55,parastr56,parastr57,parastr58,parastr59);
    p6 = Paragraph(parastr6);
    p6.Style = {OuterMargin("0pt", "0pt","20pt","10pt")};
    add(chapter,p6);
    parastr61='Some datasets are really 4 dimensional-there are the usual lat/lon spatial dimensions and verticle slices through the atmosphere.';
    parastr62=' These files will be quite large but are very useful as ghey provided much more information about vertical distribution.';
    parastr63=' It was previously noted that the data is mapped to a 2D lat lon grid, this grid is identical for all datasets.'; 
    parastr64=' As set up the grid is 576 x 361 which means that the 360 degree of longitude are mapped in 576 points.';
    parastr65=' The corresponding latitude limits of +/-90 deg are mapped into 361 points.';
    parastr66=' In practice this means that the spatial resolution is 0.5 x 0.625 deg.';
    parastr67=' As such,the grids are equally size in angular measure but not in linear extent.';
    parastr7=strcat(parastr61,parastr62,parastr63,parastr64,parastr65,parastr66,parastr67);
    p7 = Paragraph(parastr7);
    p7.Style = {OuterMargin("0pt", "0pt","20pt","10pt")};
    add(chapter,p7);
 % Add dimension chart
    imdata = imread('MerraDimensions.jpg');
    [nhigh,nwid,~]=size(imdata);
    image = mlreportgen.report.FormalImage();
    image.Image = which('MerraDimensions.jpg');
    text = Text('Merra Dimensions For Variables');
    text.Color = 'red';
    image.Caption = text;
    heightstr=strcat(num2str(nhigh/2),'px');
    widthstr=strcat(num2str(nwid/2),'px');
    image.Height = heightstr;
    image.Width = widthstr;
    image.ScaleToFit=0;
    add(chapter,image); 
    parastr71='The Table above is meant to reinforce the previous text on the dimensionality of the Merra-2 data.';
    parastr72=' 4 Dimensional data is extremely hard to look at in most applications.';
    parastr73=' For this reason it is desireable to download the Panoply Software which is freely available on the NASA EarthData Website.'; 
    parastr74=' This tool which is easy to use was indispensible in writing these Matlab scripts.';
    parastr8=strcat(parastr71,parastr72,parastr73,parastr74);
    p8 = Paragraph(parastr8);
    p8.Style = {OuterMargin("0pt", "0pt","50pt","10pt")};
    add(chapter,p8);
  % Add Table showing Instantaneous DOI Items
    parastr201='Once the user is Logged into the NASA Earthdata website the next step is to find a data collection.';
    parastr202=' There are a number of ways to search for data the Merra2 File Format document included has a number of tables to assist.';
    parastr203=' Datasets can be instantaneous,or time averaged products-chapter 6 of this document contains the above mentioned tables.'; 
    parastr204=' These tables relate the Merra 2 file collection name to a DOI (Data Objectec Identifier) which can be used to located the connection.';
    parastr21=strcat(parastr201,parastr202,parastr203,parastr204);
    p21 = Paragraph(parastr21);
    p21.Style = {OuterMargin("0pt", "0pt","20pt","10pt")};
    add(chapter,p21);
  % Add a chart to show the login page
    imdata = imread('EarthDataLogin.jpg');
    [nhigh,nwid,~]=size(imdata);
    image = mlreportgen.report.FormalImage();
    image.Image = which('EarthDataLogin.jpg');
    text = Text('View Of EarthData Login Page');
    text.Color = 'red';
    image.Caption = text;
    heightstr=strcat(num2str(nhigh/2),'px');
    widthstr=strcat(num2str(nwid/2),'px');
    image.Height = heightstr;
    image.Width = widthstr;
    image.ScaleToFit=0;
    add(chapter,image); 
    parastr211='A sample view of the login page is shown above.A user needs an account to access the data';
    parastr212=' Getting account is easy and free of charge.';
    parastr22=strcat(parastr211,parastr212);
    p22 = Paragraph(parastr22);
    p22.Style = {OuterMargin("0pt", "0pt","20pt","10pt")};
    add(chapter,p22);
    add(chapter,br);
% Show a typical view of a data collection page
    imdata = imread('DataCollectionPage.jpg');
    [nhigh,nwid,~]=size(imdata);
    image = mlreportgen.report.FormalImage();
    image.Image = which('DataCollectionPage.jpg');
    text = Text('View Of Data Collection Landing Page');
    text.Color = 'red';
    image.Caption = text;
    heightstr=strcat(num2str(nhigh/2),'px');
    widthstr=strcat(num2str(nwid/2),'px');
    image.Height = heightstr;
    image.Width = widthstr;
    image.ScaleToFit=0;
    add(chapter,image); 
    parastr221='The graphic above shows a landing page for a particular data collection';
    parastr222=' At the top of the page is a search box which was set to find item MT2MNXRAD_5.12.4';
    parastr223=' The process can be dauting to find data so the next 3 tables will show the user how this can be done.';
    parastr224=' Shortname which is a good way to find the desired collection-this is in column 2 of all the following tables.';
    parastr225=' Below the search box a wealth of data about the collection is available.';
    parastr226=' Clicking on the bottom tabs of the page can provide the user with vital data about the collection';
    parastr227=' On the side of the page is a box called Data Access which provides of number of ways to download the data.';
    parastr23=strcat(parastr221,parastr222,parastr223,parastr224,parastr225,parastr226,parastr227);
    p23 = Paragraph(parastr23);
    p23.Style = {OuterMargin("0pt", "0pt","20pt","10pt")};
    add(chapter,p23);


% Add Table 1 Part1
    add(chapter,br);
    T1=[Merra2HourlyDOIHdrs;Merra2HourlyCollection1DOITable];
    tbl1=Table(T1);
    tbl1.Style = [tbl1.Style {Border('solid','black','3px')}];
    tbl1.TableEntriesHAlign = 'center';
    tbl1.HAlign='center';
    tbl1.ColSep = 'single';
    tbl1.RowSep = 'single';
    r = row(tbl1,1);
    r.Style = [r.Style {Color('red'),Bold(true)}];
    bt1 = BaseTable(tbl1);
    tabletitle = Text('Merra2 Hourly Data Collections-Part1');
    tabletitle.Bold = false;
    bt1.Title = tabletitle;
    bt1.TableWidth="7in";
    add(chapter,bt1);
    parastr301='The image above shows the available collections that were taken with hourly frequency.';
    parastr302=' In total, there were 39 such collections and for readbility these were split into two separate tables';
    parastr303=' The landing page will provide many details to help the user decide if this is is the desired data.';
    parastr304=' Instantaneous hourly products can be on 3 hr,6h or even hourly centers';
    parastr31=strcat(parastr301,parastr302,parastr303,parastr304);
    p31= Paragraph(parastr31);
    p31.Style = {OuterMargin("0pt", "0pt","20pt","10pt")};
    add(chapter,p31);
% Add Table 1 Part2
%    add(chapter,br);
    T2=[Merra2HourlyDOIHdrs;Merra2HourlyCollection2DOITable];
    tbl2=Table(T2);
    tbl2.Style = [tbl1.Style {Border('solid','black','3px')}];
    tbl2.TableEntriesHAlign = 'center';
    tbl2.HAlign='center';
    tbl2.ColSep = 'single';
    tbl2.RowSep = 'single';
    r = row(tbl2,1);
    r.Style = [r.Style {Color('red'),Bold(true)}];
    bt2 = BaseTable(tbl2);
    tabletitle = Text('Merra2 Hourly Data Collections-Part2');
    tabletitle.Bold = false;
    bt2.Title = tabletitle;
    bt2.TableWidth="7in";
    add(chapter,bt2);
    parastr311='Note that the names of the collection usually start with inst or tavg.';
    parastr312=' If the name begins with an inst the meaning is that it is a single file or instantaneous value';
    parastr313=' On the other hand if the name starts with a tavg this means it is a time average of a number of files.';
    parastr314=' The inclusion of 1d,2d or 3d referes to the dimensionaility of the product';
    parastr315=' The use should recall that the product could have 2 horizontal components and a vertical component.';
    parastr316=' Finally the file could contain multiple time slices hence this is a 4d product.';
    parastr319=strcat(parastr311,parastr312,parastr313,parastr314,parastr315,parastr316);
    p32= Paragraph(parastr319);
    p32.Style = {OuterMargin("0pt", "0pt","20pt","10pt")};
    add(chapter,p32);
% Add the Table 2 showing monthly collections
%    add(chapter,br);
    T4=[Merra2MonthlyMeanDOIHdrs;Merra2MonthlyMeanDOITable];
    tbl4=Table(T4);
    tbl4.Style = [tbl4.Style {Border('solid','black','3px')}];
    tbl4.TableEntriesHAlign = 'center';
    tbl4.HAlign='center';
    tbl4.ColSep = 'single';
    tbl4.RowSep = 'single';
    r = row(tbl4,1);
    r.Style = [r.Style {Color('red'),Bold(true)}];
    bt4 = BaseTable(tbl4);
    tabletitle = Text('Merra2 Monthly Data Collections');
    tabletitle.Bold = false;
    bt4.Title = tabletitle;
    bt4.TableWidth="7in";
    add(chapter,bt4);
 % Add the Table 3 showing monthly diurnal mean collections
    add(chapter,br);
    T5=[Merra2MonthlyMeanDOIHdrs;Merra2MonthlyMean3DOITable];
    tbl5=Table(T5);
    tbl5.Style = [tbl5.Style {Border('solid','black','3px')}];
    tbl5.TableEntriesHAlign = 'center';
    tbl5.HAlign='center';
    tbl5.ColSep = 'single';
    tbl5.RowSep = 'single';
    r = row(tbl5,1);
    r.Style = [r.Style {Color('red'),Bold(true)}];
    bt5 = BaseTable(tbl5);
    tabletitle = Text('Merra2 Monthly Diurnal Data Collections');
    tabletitle.Bold = false;
    bt5.Title = tabletitle;
    bt5.TableWidth="7in";
    add(chapter,bt5);

    add(rpt,chapter);
%     close(rpt);
%     rptview(rpt)
    ab=2;
end

