function CreateMerra2AerosolDiagnosticsReport
% This function will create a report detailing the purpose and capabilities
% of the Aerosol Diagnostics Product for the Merra2 Program
% for the Merra2 Program
% Written By: Stephen Forczyk
% Created: Jul 20,2023
% Revised: 
%
% Classification: Unclassified


global Merra2FileName Merra2FileNames MapFormFactor;
global Merra2DataPaths Merra2Path numSelectedFiles;
global Merra2MonthlyMeanDOITable Merra2MonthlyMeanDOIHdrs;
global Merra2HourlyCollection1DOITable Merra2HourlyCollection2DOITable Merra2HourlyDOIHdrs;
global Merra2MonthlyMean3DOITable Merra2Monthly3DOITable Merra2HourlyDOIHdrs;
global Merra2AerosolHdrs Merra2BlackCarbonAerosolTable Merra2DustTable;
global AerosolEmissionsHdr AerosolEmissionsTable;
global VariableTableBC VariableTableHdr VariableTableDustPt1 VariableTableDustPt2;
global VariableTableOC VariableTableSulfatesPt1 VariableTableSulfatesPt2;

global RptGenPresent iCreatePDFReport pdffilename rpt chapter tocc lof lot;
global JpegCounter JpegFileList;
global ImageProcessPresent iGOES;
global iReport ifixedImagePaths;
global iSubMean iCheckConfig;
global MonthDayStr MonthDayYearStr YearMonthStr;
global WorldCityFileName World200TopCities;
global iCityPlot maxCities;
global PressureFileName;
global SelectedFiles numSelectedFiles path1;

global fid;
global widd2 lend2;
global initialtimestr igrid ijpeg ilog imovie;
global vert1 hor1 widd lend;
global vert2 hor2 machine;
global chart_time;
global Fz1 Fz2;
global idirector mov izoom iwindow;

global matpath datapath;
global jpegpath tiffpath moviepath savepath;
global excelpath ascpath citypath tablepath;
global ipowerpoint PowerPointFile scaling stretching padding;
global ichartnum;
global ColorList RGBVals ColorList2 xkcdVals LandColors;
global orange bubblegum brown brightblue;
% additional paths needed for mapping
global pdfpath govjpegpath;

global DayMonthNonLeapYear DayMonthLeapYear CalendarFileName;
global pwd;

import mlreportgen.dom.*;
import mlreportgen.report.*;
import mlreportgen.utils.*
%% Build some tables
% Start with the Hourly data but break this up into 2 tables because of the
% length

Merra2BlackCarbonAerosolTable=cell(14,5);
Merra2DustTable=cell(28,5);
Merra2AerosolHdrs=cell(1,5);
Merra2AerosolHdrs{1,1}='List Number';
Merra2AerosolHdrs{1,2}='Short Name';
Merra2AerosolHdrs{1,3}='Description';
Merra2AerosolHdrs{1,4}='Units';
Merra2AerosolHdrs{1,5}='ikind value';
Merra2BlackCarbonAerosolTable{1,1}='1';
Merra2BlackCarbonAerosolTable{1,2}='BCDP001';
Merra2BlackCarbonAerosolTable{1,3}='Black Carbon Dry Deposition Bin 01';
Merra2BlackCarbonAerosolTable{1,4}='kg/m^2/sec';
Merra2BlackCarbonAerosolTable{1,5}='1';
Merra2BlackCarbonAerosolTable{2,1}='2';
Merra2BlackCarbonAerosolTable{2,2}='BCDP002';
Merra2BlackCarbonAerosolTable{2,3}='Black Carbon Dry Deposition Bin 02';
Merra2BlackCarbonAerosolTable{2,4}='kg/m^2/sec';
Merra2BlackCarbonAerosolTable{2,5}='2';
Merra2BlackCarbonAerosolTable{3,1}='3';
Merra2BlackCarbonAerosolTable{3,2}='BCEM001';
Merra2BlackCarbonAerosolTable{3,3}='Black Carbon Emission Bin 01';
Merra2BlackCarbonAerosolTable{3,4}='kg/m^2/sec';
Merra2BlackCarbonAerosolTable{3,5}='3';
Merra2BlackCarbonAerosolTable{4,1}='4';
Merra2BlackCarbonAerosolTable{4,2}='BCEM002';
Merra2BlackCarbonAerosolTable{4,3}='Black Carbon Emission Bin 02';
Merra2BlackCarbonAerosolTable{4,4}='kg/m^2/sec';
Merra2BlackCarbonAerosolTable{4,5}='4';
Merra2BlackCarbonAerosolTable{5,1}='5';
Merra2BlackCarbonAerosolTable{5,2}='BCEMAN';
Merra2BlackCarbonAerosolTable{5,3}='Black Carbon Anthropogenic Emission';
Merra2BlackCarbonAerosolTable{5,4}='kg/m^2/sec';
Merra2BlackCarbonAerosolTable{5,5}='5';
Merra2BlackCarbonAerosolTable{6,1}='6';
Merra2BlackCarbonAerosolTable{6,2}='BCEMBB';
Merra2BlackCarbonAerosolTable{6,3}='Black Carbon Biomass Emissions';
Merra2BlackCarbonAerosolTable{6,4}='kg/m^2/sec';
Merra2BlackCarbonAerosolTable{6,5}='6';
Merra2BlackCarbonAerosolTable{7,1}='7';
Merra2BlackCarbonAerosolTable{7,2}='BCEMBF';
Merra2BlackCarbonAerosolTable{7,3}='Black Carbon Biofuel Emissions';
Merra2BlackCarbonAerosolTable{7,4}='kg/m^2/sec';
Merra2BlackCarbonAerosolTable{7,5}='7';
Merra2BlackCarbonAerosolTable{8,1}='8';
Merra2BlackCarbonAerosolTable{8,2}='BCHYPHIL';
Merra2BlackCarbonAerosolTable{8,3}='Black Carbon Hydrophobic To Hydrophilic';
Merra2BlackCarbonAerosolTable{8,4}='kg/m^2/sec';
Merra2BlackCarbonAerosolTable{8,5}='8';
Merra2BlackCarbonAerosolTable{9,1}='9';
Merra2BlackCarbonAerosolTable{9,2}='BCSD001';
Merra2BlackCarbonAerosolTable{9,3}='Black Carbon Sedimentation Bin 01';
Merra2BlackCarbonAerosolTable{9,4}='kg/m^2/sec';
Merra2BlackCarbonAerosolTable{9,5}='9';
Merra2BlackCarbonAerosolTable{10,1}='10';
Merra2BlackCarbonAerosolTable{10,2}='BCSD002';
Merra2BlackCarbonAerosolTable{10,3}='Black Carbon Sedimentation Bin 02';
Merra2BlackCarbonAerosolTable{10,4}='kg/m^2/sec';
Merra2BlackCarbonAerosolTable{10,5}='10';
Merra2BlackCarbonAerosolTable{11,1}='11';
Merra2BlackCarbonAerosolTable{11,2}='BCSV001';
Merra2BlackCarbonAerosolTable{11,3}='Black Carbon Convective Scavenging Bin 01';
Merra2BlackCarbonAerosolTable{11,4}='kg/m^2/sec';
Merra2BlackCarbonAerosolTable{11,5}='11';
Merra2BlackCarbonAerosolTable{12,1}='12';
Merra2BlackCarbonAerosolTable{12,2}='BCSV002';
Merra2BlackCarbonAerosolTable{12,3}='Black Carbon Convective Scavenging Bin 02';
Merra2BlackCarbonAerosolTable{12,4}='kg/m^2/sec';
Merra2BlackCarbonAerosolTable{12,5}='12';
Merra2BlackCarbonAerosolTable{13,1}='13';
Merra2BlackCarbonAerosolTable{13,2}='BCWT001';
Merra2BlackCarbonAerosolTable{13,3}='Black Carbon Wet Deposition Bin 01';
Merra2BlackCarbonAerosolTable{13,4}='kg/m^2/sec';
Merra2BlackCarbonAerosolTable{13,5}='13';
Merra2BlackCarbonAerosolTable{14,1}='14';
Merra2BlackCarbonAerosolTable{14,2}='BCWT002';
Merra2BlackCarbonAerosolTable{14,3}='Black Carbon Wet Deposition Bin 02';
Merra2BlackCarbonAerosolTable{14,4}='kg/m^2/sec';
Merra2BlackCarbonAerosolTable{14,5}='14';
Merra2DustTable{1,1}='1';
Merra2DustTable{2,1}='DUAERIDX';
Merra2DustTable{1,3}='DUST TOMS UV Index';
Merra2DustTable{1,4}='dimensionless';
Merra2DustTable{1,5}='15';
Merra2DustTable{2,1}='2';
Merra2DustTable{2,2}='DUDP001';
Merra2DustTable{2,3}='Dry Dust Deposition Bin 01';
Merra2DustTable{2,4}='kg/m^2/sec';
Merra2DustTable{2,5}='16';
Merra2DustTable{3,1}='3';
Merra2DustTable{3,2}='DUDP002';
Merra2DustTable{3,3}='Dry Dust Deposition Bin 02';
Merra2DustTable{3,4}='kg/m^2/sec';
Merra2DustTable{3,5}='17';
Merra2DustTable{4,1}='4';
Merra2DustTable{4,2}='DUDP003';
Merra2DustTable{4,3}='Dry Dust Deposition Bin 03';
Merra2DustTable{4,4}='kg/m^2/sec';
Merra2DustTable{4,5}='18';
Merra2DustTable{5,1}='5';
Merra2DustTable{5,2}='DUDP004';
Merra2DustTable{5,3}='Dry Dust Deposition Bin 03';
Merra2DustTable{5,4}='kg/m^2/sec';
Merra2DustTable{5,5}='19';
Merra2DustTable{6,1}='6';
Merra2DustTable{6,2}='DUDP005';
Merra2DustTable{6,3}='Dry Dust Deposition Bin 04';
Merra2DustTable{6,4}='kg/m^2/sec';
Merra2DustTable{6,5}='20';
Merra2DustTable{7,1}='7';
Merra2DustTable{7,2}='DUEM001';
Merra2DustTable{7,3}='Dust Emission Bin 01';
Merra2DustTable{7,4}='kg/m^2/sec';
Merra2DustTable{7,5}='21';
Merra2DustTable{8,1}='8';
Merra2DustTable{8,2}='DUEM002';
Merra2DustTable{8,3}='Dust Emission Bin 02';
Merra2DustTable{8,4}='kg/m^2/sec';
Merra2DustTable{8,5}='22';
Merra2DustTable{9,1}='9';
Merra2DustTable{9,2}='DUEM003';
Merra2DustTable{9,3}='Dust Emission Bin 03';
Merra2DustTable{9,4}='kg/m^2/sec';
Merra2DustTable{9,5}='23';
Merra2DustTable{10,1}='10';
Merra2DustTable{10,2}='DUEM004';
Merra2DustTable{10,3}='Dust Emission Bin 04';
Merra2DustTable{10,4}='kg/m^2/sec';
Merra2DustTable{10,5}='24';
Merra2DustTable{11,1}='11';
Merra2DustTable{11,2}='DUEM005';
Merra2DustTable{11,3}='Dust Emission Bin 05';
Merra2DustTable{11,4}='kg/m^2/sec';
Merra2DustTable{11,5}='25';
Merra2DustTable{12,1}='12';
Merra2DustTable{12,2}='DUEXTTFM';
Merra2DustTable{12,3}='Dust Extinction .55 microns';
Merra2DustTable{12,4}='dimensionless';
Merra2DustTable{12,5}='26';
Merra2DustTable{13,1}='13';
Merra2DustTable{13,2}='DUSCATFM';
Merra2DustTable{13,3}='Dust Scattering .55 microns';
Merra2DustTable{13,4}='dimensionless';
Merra2DustTable{13,5}='27';
Merra2DustTable{14,1}='14';
Merra2DustTable{14,2}='DUSD001';
Merra2DustTable{14,3}='Dust Sedimentation Bin 01';
Merra2DustTable{14,4}='kg/m^2/sec';
Merra2DustTable{14,5}='28';
Merra2DustTable{15,1}='15';
Merra2DustTable{15,2}='DUSD002';
Merra2DustTable{15,3}='Dust Sedimentation Bin 02';
Merra2DustTable{15,4}='kg/m^2/sec';
Merra2DustTable{15,5}='29';
Merra2DustTable{16,1}='16';
Merra2DustTable{16,2}='DUSD003';
Merra2DustTable{16,3}='Dust Sedimentation Bin 03';
Merra2DustTable{16,4}='kg/m^2/sec';
Merra2DustTable{16,5}='30';
Merra2DustTable{17,1}='17';
Merra2DustTable{17,2}='DUSD004';
Merra2DustTable{17,3}='Dust Sedimentation Bin 04';
Merra2DustTable{17,4}='kg/m^2/sec';
Merra2DustTable{17,5}='31';
Merra2DustTable{18,1}='18';
Merra2DustTable{18,2}='DUSD005';
Merra2DustTable{18,3}='Dust Sedimentation Bin 05';
Merra2DustTable{18,4}='kg/m^2/sec';
Merra2DustTable{18,5}='32';
Merra2DustTable{19,1}='19';
Merra2DustTable{19,2}='DUSV001';
Merra2DustTable{19,3}='Dust Scavenging Bin 01';
Merra2DustTable{19,4}='kg/m^2/sec';
Merra2DustTable{19,5}='33';
Merra2DustTable{20,1}='20';
Merra2DustTable{20,2}='DUSV002';
Merra2DustTable{20,3}='Dust Scavenging Bin 02';
Merra2DustTable{20,4}='kg/m^2/sec';
Merra2DustTable{20,5}='34';
Merra2DustTable{21,1}='21';
Merra2DustTable{21,2}='DUSV003';
Merra2DustTable{21,3}='Dust Scavenging Bin 03';
Merra2DustTable{21,4}='kg/m^2/sec';
Merra2DustTable{21,5}='35';
Merra2DustTable{22,1}='22';
Merra2DustTable{22,2}='DUSV004';
Merra2DustTable{22,3}='Dust Scavenging Bin 04';
Merra2DustTable{22,4}='kg/m^2/sec';
Merra2DustTable{22,5}='36';
Merra2DustTable{23,1}='23';
Merra2DustTable{23,2}='DUSV005';
Merra2DustTable{23,3}='Dust Scavenging Bin 05';
Merra2DustTable{23,4}='kg/m^2/sec';
Merra2DustTable{23,5}='37';
Merra2DustTable{24,1}='24';
Merra2DustTable{24,2}='DUWT001';
Merra2DustTable{24,3}='Dust Wet Deposition Bin 01';
Merra2DustTable{24,4}='kg/m^2/sec';
Merra2DustTable{24,5}='38';
Merra2DustTable{25,1}='25';
Merra2DustTable{25,2}='DUWT002';
Merra2DustTable{25,3}='Dust Wet Deposition Bin 02';
Merra2DustTable{25,4}='kg/m^2/sec';
Merra2DustTable{25,5}='39';
Merra2DustTable{26,1}='26';
Merra2DustTable{26,2}='DUWT003';
Merra2DustTable{26,3}='Dust Wet Deposition Bin 03';
Merra2DustTable{26,4}='kg/m^2/sec';
Merra2DustTable{26,5}='40';
Merra2DustTable{27,1}='27';
Merra2DustTable{27,2}='DUWT004';
Merra2DustTable{27,3}='Dust Wet Deposition Bin 04';
Merra2DustTable{27,4}='kg/m^2/sec';
Merra2DustTable{27,5}='41';
Merra2DustTable{28,1}='28';
Merra2DustTable{28,2}='DUWT005';
Merra2DustTable{28,3}='Dust Wet Deposition Bin 05';
Merra2DustTable{28,4}='kg/m^2/sec';
Merra2DustTable{28,5}='42';
Merra2HourlyCollection2DOITable=cell(19,3);
Merra2MonthlyMean3DOITable=cell(26,3);
Merra2HourlyDOIHdrs=cell(1,3);
Merra2HourlyDOIHdrs{1,1}='Descriptive ShortFileName';
Merra2HourlyDOIHdrs{1,2}='Short Name';
Merra2HourlyDOIHdrs{1,3}='DOI Name';
Merra2HourlyCollection1DOITable{1,1}='inst1_2d_asm_Nx';
Merra2HourlyCollection1DOITable{1,2}='M2I1NXASM';
Merra2HourlyCollection1DOITable{1,3}='10.5067/3Z173KIE2TPD';
Merra2HourlyCollection1DOITable{2,1}='inst1_2d_int_Nx';
Merra2HourlyCollection1DOITable{2,2}='M2I1NXINT';
Merra2HourlyCollection1DOITable{2,3}='10.5067/G0U6NGQ3BLE0';
Merra2HourlyCollection1DOITable{3,1}='inst1_2d_lfo_Nx';
Merra2HourlyCollection1DOITable{3,2}='M2I1NXLFO';
Merra2HourlyCollection1DOITable{3,3}='10.5067/RCMZA6TL70BG';
Merra2HourlyCollection1DOITable{4,1}='inst3_3d_asm_Np';
Merra2HourlyCollection1DOITable{4,2}='M2I3NPASM';
Merra2HourlyCollection1DOITable{4,3}='10.5067/QBZ6MG944HW0';
Merra2HourlyCollection1DOITable{5,1}='inst3_3d_aer_Nv';
Merra2HourlyCollection1DOITable{5,2}='M2I3NVAER';
Merra2HourlyCollection1DOITable{5,3}='10.5067/LTVB4GPCOTK2';
Merra2HourlyCollection1DOITable{6,1}='inst3_3d_asm_Nv';
Merra2HourlyCollection1DOITable{6,2}='M2I3NVASM';
Merra2HourlyCollection1DOITable{6,3}='10.5067/WWQSXQ8IVFW8';
Merra2HourlyCollection1DOITable{7,1}='inst3_3d_chm_Nv';
Merra2HourlyCollection1DOITable{7,2}='M2I3NVCHM';
Merra2HourlyCollection1DOITable{7,3}='10.5067/HO9OVZWF3KW2';
Merra2HourlyCollection1DOITable{8,1}='inst3_3d_gas_Nv';
Merra2HourlyCollection1DOITable{8,2}='M2I3NVGAS';
Merra2HourlyCollection1DOITable{8,3}='10.5067/96BUID8HGGX5';
Merra2HourlyCollection1DOITable{9,1}='inst3_2d_gas_Nx';
Merra2HourlyCollection1DOITable{9,2}='M2I3NXGAS';
Merra2HourlyCollection1DOITable{9,3}='10.5067/HNGA0EWW0R09';
Merra2HourlyCollection1DOITable{10,1}='inst6_3d_ana_Np';
Merra2HourlyCollection1DOITable{10,2}='M2I6NPANA';
Merra2HourlyCollection1DOITable{10,3}='10.5067/A7S6XP56VZWS';
Merra2HourlyCollection1DOITable{11,1}='inst6_3d_ana_Nv';
Merra2HourlyCollection1DOITable{11,2}='M2I6NVANA';
Merra2HourlyCollection1DOITable{11,3}='10.5067/IUUF4WB9FT4W';
Merra2HourlyCollection1DOITable{12,1}='statD_2d_slv_Nx';
Merra2HourlyCollection1DOITable{12,2}='M2SDNXSLV';
Merra2HourlyCollection1DOITable{12,3}='10.5067/9SC1VNTWGWV3';
Merra2HourlyCollection1DOITable{13,1}='tavg1_2d_adg_Nx';
Merra2HourlyCollection1DOITable{13,2}='M2T1NXADG';
Merra2HourlyCollection1DOITable{13,3}='10.5067/HM00OHQBHKTP';
Merra2HourlyCollection1DOITable{14,1}='tavg1_2d_aer_Nx';
Merra2HourlyCollection1DOITable{14,2}='M2T1NXAER';
Merra2HourlyCollection1DOITable{14,3}='10.5067/KLICLTZ8EM9D';
Merra2HourlyCollection1DOITable{15,1}='tavg1_2d_chm_Nx';
Merra2HourlyCollection1DOITable{15,2}='M2T1NXCHM';
Merra2HourlyCollection1DOITable{15,3}='10.5067/3RQ5YS674DGQ';
Merra2HourlyCollection1DOITable{16,1}='tavg1_2d_csp_Nx';
Merra2HourlyCollection1DOITable{16,2}='M2T1NXCSP';
Merra2HourlyCollection1DOITable{16,3}='10.5067/H0VVAD8F6MX5';
Merra2HourlyCollection1DOITable{17,1}='tavg1_2d_flx_Nx';
Merra2HourlyCollection1DOITable{17,2}='M2T1NXFLX';
Merra2HourlyCollection1DOITable{17,3}='10.5067/7MCPBJ41Y0K6';
Merra2HourlyCollection1DOITable{18,1}='tavg1_2d_int_Nx';
Merra2HourlyCollection1DOITable{18,2}='M2T1NXINT';
Merra2HourlyCollection1DOITable{18,3}='10.5067/Q5GVUVUIVGO7';
Merra2HourlyCollection1DOITable{19,1}='tavg1_2d_lfo_Nx';
Merra2HourlyCollection1DOITable{19,2}='M2T1NXLFO';
Merra2HourlyCollection1DOITable{19,3}='10.5067/L0T5GEG1NYFA';
Merra2HourlyCollection1DOITable{20,1}='tavg1_2d_lnd_Nx';
Merra2HourlyCollection1DOITable{20,2}='M2T1NXLND';
Merra2HourlyCollection1DOITable{20,3}='10.5067/RKPHT8KC1Y1T';
Merra2HourlyCollection2DOITable{1,1}='tavg1_2d_ocn_Nx';
Merra2HourlyCollection2DOITable{1,2}='M2T1NXOCN';
Merra2HourlyCollection2DOITable{1,3}='10.5067/Y67YQ1L3ZZ4R';
Merra2HourlyCollection2DOITable{2,1}='tavg1_2d_rad_Nx';
Merra2HourlyCollection2DOITable{2,2}='M2T1NXRAD';
Merra2HourlyCollection2DOITable{2,3}='10.5067/Q9QMY5PBNV1T';
Merra2HourlyCollection2DOITable{3,1}='tavg1_2d_slv_Nx';
Merra2HourlyCollection2DOITable{3,2}='M2T1NXSLV';
Merra2HourlyCollection2DOITable{3,3}='10.5067/VJAFPLI1CSIV';
Merra2HourlyCollection2DOITable{4,1}='tavg3_3d_mst_Ne';
Merra2HourlyCollection2DOITable{4,2}='M2T3NEMST';
Merra2HourlyCollection2DOITable{4,3}='10.5067/JRUZ3SJ3ZJ72';
Merra2HourlyCollection2DOITable{5,1}='tavg3_3d_trb_Ne';
Merra2HourlyCollection2DOITable{5,2}='M2T3NETRB';
Merra2HourlyCollection2DOITable{5,3}='10.5067/4I7ZI35QRH8K';
Merra2HourlyCollection2DOITable{6,1}='tavg3_3d_nav_Ne';
Merra2HourlyCollection2DOITable{6,2}='M2T3NENAV';
Merra2HourlyCollection2DOITable{6,3}='10.5067/N5WAKNS1UYQN';
Merra2HourlyCollection2DOITable{7,1}='tavg3_3d_cld_Np';
Merra2HourlyCollection2DOITable{7,2}='M2T3NPCLD';
Merra2HourlyCollection2DOITable{7,3}='10.5067/TX10URJSKT53';
Merra2HourlyCollection2DOITable{8,1}='tavg3_3d_mst_Np';
Merra2HourlyCollection2DOITable{8,2}='M2T3NPMST';
Merra2HourlyCollection2DOITable{8,3}='10.5067/0TUFO90Q2PMS';
Merra2HourlyCollection2DOITable{9,1}='tavg3_3d_rad_Np';
Merra2HourlyCollection2DOITable{9,2}='M2T3NPRAD';
Merra2HourlyCollection2DOITable{9,3}='10.5067/3UGE8WQXZAOK';
Merra2HourlyCollection2DOITable{10,1}='tavg3_3d_tdt_Np';
Merra2HourlyCollection2DOITable{10,2}='M2T3NPTDT';
Merra2HourlyCollection2DOITable{10,3}='10.5067/9NCR9DDDOPFI';
Merra2HourlyCollection2DOITable{11,1}='tavg3_3d_trb_Np';
Merra2HourlyCollection2DOITable{11,2}='M2T3NPTRB';
Merra2HourlyCollection2DOITable{11,3}='10.5067/ZRRJPGWL8AVL';
Merra2HourlyCollection2DOITable{12,1}='tavg3_3d_udt_Np';
Merra2HourlyCollection2DOITable{12,2}='M2T3NPUDT';
Merra2HourlyCollection2DOITable{12,3}='10.5067/CWV0G3PPPWFW';
Merra2HourlyCollection2DOITable{13,1}='tavg3_3d_odt_Np';
Merra2HourlyCollection2DOITable{13,2}='M2T3NPODT';
Merra2HourlyCollection2DOITable{13,3}='10.5067/S0LYTK57786Z';
Merra2HourlyCollection2DOITable{14,1}='tavg3_3d_qdt_Np';
Merra2HourlyCollection2DOITable{14,2}='M2T3NPQDT';
Merra2HourlyCollection2DOITable{14,3}='10.5067/A9KWADY78YHQ';
Merra2HourlyCollection2DOITable{15,1}='tavg3_3d_asm_Nv';
Merra2HourlyCollection2DOITable{15,2}='M2T3NVASM';
Merra2HourlyCollection2DOITable{15,3}='10.5067/SUOQESM06LPK';
Merra2HourlyCollection2DOITable{16,1}='tavg3_3d_cld_Nv';
Merra2HourlyCollection2DOITable{16,2}='M2T3NVCLD';
Merra2HourlyCollection2DOITable{16,3}='10.5067/F9353J0FAHIH';
Merra2HourlyCollection2DOITable{17,1}='tavg3_3d_mst_Nv';
Merra2HourlyCollection2DOITable{17,2}='M2T3NVMST';
Merra2HourlyCollection2DOITable{17,3}='10.5067/ZXTJ28TQR1TR';
Merra2HourlyCollection2DOITable{18,1}='tavg3_3d_rad_Nv';
Merra2HourlyCollection2DOITable{18,2}='M2T3NVRAD';
Merra2HourlyCollection2DOITable{18,3}='10.5067/7GFQKO1T43RW';
Merra2HourlyCollection2DOITable{19,1}='tavg3_2d_glc_Nx';
Merra2HourlyCollection2DOITable{19,2}='M2T3NXGLC';
Merra2HourlyCollection2DOITable{19,3}='10.5067/9ETB4TT5J6US';
% Next create the Monthly Averaged Data Tables
Merra2MonthlyMeanDOITable=cell(28,3);
Merra2MonthlyMeanDOIHdrs=cell(1,3);
Merra2MonthlyMeanDOIHdrs{1,1}='Descriptive ShortFileName';
Merra2MonthlyMeanDOIHdrs{1,2}='Short Name';
Merra2MonthlyMeanDOIHdrs{1,3}='DOI Name';

Merra2MonthlyMeanDOITable{1,1}='instM_2d_asm_Nx';
Merra2MonthlyMeanDOITable{1,2}='M2IMNXASM';
Merra2MonthlyMeanDOITable{1,3}='10.5067/5ESKGQTZG7FO';
Merra2MonthlyMeanDOITable{2,1}='instM_2d_int_Nx';
Merra2MonthlyMeanDOITable{2,2}='M2IMNXINT';
Merra2MonthlyMeanDOITable{2,3}='10.5067/KVTU1A8BWFSJ';
Merra2MonthlyMeanDOITable{3,1}='instM_2d_lfo_Nx';
Merra2MonthlyMeanDOITable{3,2}='M2IMNXLFO';
Merra2MonthlyMeanDOITable{3,3}='10.5067/11F99Y6TXN99';
Merra2MonthlyMeanDOITable{4,1}='instM_2d_gas_Nx';
Merra2MonthlyMeanDOITable{4,2}='M2IMNXGAS';
Merra2MonthlyMeanDOITable{4,3}='10.5067/XOGNBQEPLUC5';
Merra2MonthlyMeanDOITable{5,1}='instM_3d_asm_Np';
Merra2MonthlyMeanDOITable{5,2}='M2IMNPASM';
Merra2MonthlyMeanDOITable{5,3}='10.5067/2E096JV59PK7';
Merra2MonthlyMeanDOITable{6,1}='instM_3d_ana_Np';
Merra2MonthlyMeanDOITable{6,2}='M2IMNPANA';
Merra2MonthlyMeanDOITable{6,3}='10.5067/V92O8XZ30XBI';
Merra2MonthlyMeanDOITable{7,1}='tavgM_2d_adg_Nx';
Merra2MonthlyMeanDOITable{7,2}='M2TMNXADG';
Merra2MonthlyMeanDOITable{7,3}='10.5067/RZIK2TV7PP38';
Merra2MonthlyMeanDOITable{8,1}='tavgM_2d_aer_Nx';
Merra2MonthlyMeanDOITable{8,2}='M2TMNXAER';
Merra2MonthlyMeanDOITable{8,3}='10.5067/FH9A0MLJPC7N';
Merra2MonthlyMeanDOITable{9,1}='tavgM_2d_chm_Nx';
Merra2MonthlyMeanDOITable{9,2}='M2TMNXCHM';
Merra2MonthlyMeanDOITable{9,3}='10.5067/WMT31RKEXK8I';
Merra2MonthlyMeanDOITable{10,1}='tavgM_2d_csp_Nx';
Merra2MonthlyMeanDOITable{10,2}='M2TMNXCSP';
Merra2MonthlyMeanDOITable{10,3}='10.5067/BZPOTGJOQKLU';
Merra2MonthlyMeanDOITable{11,1}='tavgM_2d_flx_Nx';
Merra2MonthlyMeanDOITable{11,2}='M2TMNXFLX';
Merra2MonthlyMeanDOITable{11,3}='10.5067/0JRLVL8YV2Y4';
Merra2MonthlyMeanDOITable{12,1}='tavgM_2d_int_Nx';
Merra2MonthlyMeanDOITable{12,2}='M2TMNXINT';
Merra2MonthlyMeanDOITable{12,3}='10.5067/FQPTQ4OJ22TL';
Merra2MonthlyMeanDOITable{13,1}='tavgM_2d_lfo_Nx';
Merra2MonthlyMeanDOITable{13,2}='M2TMNXLFO';
Merra2MonthlyMeanDOITable{13,3}='10.5067/5V7K6LJD44SY';
Merra2MonthlyMeanDOITable{14,1}='tavgM_2d_lnd_Nx';
Merra2MonthlyMeanDOITable{14,2}='M2TMNXLND';
Merra2MonthlyMeanDOITable{14,3}='10.5067/8S35XF81C28F';
Merra2MonthlyMeanDOITable{15,1}='tavgM_2d_ocn_Nx';
Merra2MonthlyMeanDOITable{15,2}='M2TMNXOCN';
Merra2MonthlyMeanDOITable{15,3}='10.5067/4IASLIDL8EEC';
Merra2MonthlyMeanDOITable{16,1}='tavgM_2d_rad_Nx';
Merra2MonthlyMeanDOITable{16,2}='M2TMNXRAD';
Merra2MonthlyMeanDOITable{16,3}='10.5067/OU3HJDS973O0';
Merra2MonthlyMeanDOITable{17,1}='tavgM_2d_slv_Nx';
Merra2MonthlyMeanDOITable{17,2}='M2TMNXSLV';
Merra2MonthlyMeanDOITable{17,3}='10.5067/AP1B0BA5PD2K';
Merra2MonthlyMeanDOITable{18,1}='tavgM_2d_glc_Nx';
Merra2MonthlyMeanDOITable{18,2}='M2TMNXGLC';
Merra2MonthlyMeanDOITable{18,3}='10.5067/5W8Q3I9WUFGX';
Merra2MonthlyMeanDOITable{19,1}='tavgM_3d_cld_Np';
Merra2MonthlyMeanDOITable{19,2}='M2TMNPCLD';
Merra2MonthlyMeanDOITable{19,3}='10.5067/J9R0LXGH48JR';
Merra2MonthlyMeanDOITable{20,1}='tavgM_3d_mst_Np';
Merra2MonthlyMeanDOITable{20,2}='M2TMNPMST';
Merra2MonthlyMeanDOITable{20,3}='10.5067/ZRZGD0DCK1CG';
Merra2MonthlyMeanDOITable{21,1}='tavgM_3d_rad_Np';
Merra2MonthlyMeanDOITable{21,2}='M2TMNPRAD';
Merra2MonthlyMeanDOITable{21,3}='10.5067/H3YGROBVBGFJ';
Merra2MonthlyMeanDOITable{22,1}='tavgM_3d_tdt_Np';
Merra2MonthlyMeanDOITable{22,2}='M2TMNPTDT';
Merra2MonthlyMeanDOITable{22,3}='10.5067/VILT59HI2MOY';
Merra2MonthlyMeanDOITable{23,1}='tavgM_3d_trb_Np';
Merra2MonthlyMeanDOITable{23,2}='M2TMNPTRB';
Merra2MonthlyMeanDOITable{23,3}='10.5067/2YOIQB5C3ACN';
Merra2MonthlyMeanDOITable{24,1}='tavgM_3d_udt_Np';
Merra2MonthlyMeanDOITable{24,2}='M2TMNPUDT';
Merra2MonthlyMeanDOITable{24,3}='10.5067/YSR6IA5057XX';
Merra2MonthlyMeanDOITable{25,1}='tavgM_3d_odt_Np';
Merra2MonthlyMeanDOITable{25,2}='M2TMNPODT';
Merra2MonthlyMeanDOITable{25,3}='10.5067/Z2KCWAV4GPD2';
Merra2MonthlyMeanDOITable{26,1}='tavgM_3d_qdt_Np';
Merra2MonthlyMeanDOITable{26,2}='M2TMNPQDT';
Merra2MonthlyMeanDOITable{26,3}='10.5067/2ZTU87V69ATP';
Merra2MonthlyMeanDOITable{27,1}='statM_2d_slv_Nx';
Merra2MonthlyMeanDOITable{27,2}='M2SMNXSLV';
Merra2MonthlyMeanDOITable{27,3}='10.5067/KVIMOMCUO83U';
Merra2MonthlyMeanDOITable{28,1}='const_2d_asm_NX';
Merra2MonthlyMeanDOITable{28,2}='M2C0NXASM';
Merra2MonthlyMeanDOITable{28,3}='10.5067/ME5QX6Q5IGGU';
% Finally create the Monthly Mean Diurnal Tables
Merra2MonthlyMean3DOITable{1,1}='instU_2d_asm_Nx';
Merra2MonthlyMean3DOITable{1,2}='M2IUNXASM';
Merra2MonthlyMean3DOITable{1,3}='10.5067/BOJSTZAO2L8R';
Merra2MonthlyMean3DOITable{2,1}='instU_2d_int_Nx';
Merra2MonthlyMean3DOITable{2,2}='M2IUNXINT';
Merra2MonthlyMean3DOITable{2,3}='10.5067/DGAB3HFEYMLY';
Merra2MonthlyMean3DOITable{3,1}='instU_2d_lfo_Nx';
Merra2MonthlyMean3DOITable{3,2}='M2IUNXLFO';
Merra2MonthlyMean3DOITable{3,3}='10.5067/FC3BVJ88Y8A2';
Merra2MonthlyMean3DOITable{4,1}='instU_2d_gas_Nx';
Merra2MonthlyMean3DOITable{4,2}='M2IUNXGAS';
Merra2MonthlyMean3DOITable{4,3}='10.5067/TVJ4MHBED39L';
Merra2MonthlyMean3DOITable{5,1}='instU_3d_asm_Np';
Merra2MonthlyMean3DOITable{5,2}='M2IUNPASM';
Merra2MonthlyMean3DOITable{5,3}='10.5067/6EGRBNEBMIYS';
Merra2MonthlyMean3DOITable{6,1}='instU_3d_ana_Np';
Merra2MonthlyMean3DOITable{6,2}='M2IUNPANA';
Merra2MonthlyMean3DOITable{6,3}='10.5067/TRD91YO9S6E7';
Merra2MonthlyMean3DOITable{7,1}='tavgU_2d_adg_Nx';
Merra2MonthlyMean3DOITable{7,2}='M2TUNXADG';
Merra2MonthlyMean3DOITable{7,3}='10.5067/YZJJXZTFCX6B';
Merra2MonthlyMean3DOITable{8,1}='tavgU_2d_aer_Nx';
Merra2MonthlyMean3DOITable{8,2}='M2TUNXAER';
Merra2MonthlyMean3DOITable{8,3}='10.5067/KPUMVXFEQLA1';
Merra2MonthlyMean3DOITable{9,1}='tavgU_2d_chm_Nx';
Merra2MonthlyMean3DOITable{9,2}='M2TUNXCHM';
Merra2MonthlyMean3DOITable{9,3}='10.5067/5KFZ6GXRHZKN';
Merra2MonthlyMean3DOITable{10,1}='tavgU_2d_csp_Nx';
Merra2MonthlyMean3DOITable{10,2}='M2TUNXCSP';
Merra2MonthlyMean3DOITable{10,3}='10.5067/9PH5QU4CL9E8';
Merra2MonthlyMean3DOITable{11,1}='tavgU_2d_flx_Nx';
Merra2MonthlyMean3DOITable{11,2}='M2TUNXFLX';
Merra2MonthlyMean3DOITable{11,3}='10.5067/LUHPNWAKYIO3';
Merra2MonthlyMean3DOITable{12,1}='tavgU_2d_int_Nx';
Merra2MonthlyMean3DOITable{12,2}='M2TUNXINT';
Merra2MonthlyMean3DOITable{12,3}='10.5067/R2MPVU4EOSWT';
Merra2MonthlyMean3DOITable{13,1}='tavgU_2d_lfo_Nx';
Merra2MonthlyMean3DOITable{13,2}='M2TUNXLFO';
Merra2MonthlyMean3DOITable{13,3}='10.5067/BTSNKAJND3ME';
Merra2MonthlyMean3DOITable{14,1}='tavgU_2d_lnd_Nx';
Merra2MonthlyMean3DOITable{14,2}='M2TUNXLND';
Merra2MonthlyMean3DOITable{14,3}='10.5067/W0J15047CF6N';
Merra2MonthlyMean3DOITable{15,1}='tavgU_2d_ocn_Nx';
Merra2MonthlyMean3DOITable{15,2}='M2TUNXOCN';
Merra2MonthlyMean3DOITable{15,3}='10.5067/KLNAVGAX7J66';
Merra2MonthlyMean3DOITable{16,1}='tavgU_2d_rad_Nx';
Merra2MonthlyMean3DOITable{16,2}='M2TUNXRAD';
Merra2MonthlyMean3DOITable{16,3}='10.5067/4SDCJYK8P9QU';
Merra2MonthlyMean3DOITable{17,1}='tavgU_2d_slv_Nx';
Merra2MonthlyMean3DOITable{17,2}='M2TUNXSLV';
Merra2MonthlyMean3DOITable{17,3}='10.5067/AFOK0TPEVQEK';
Merra2MonthlyMean3DOITable{18,1}='tavgU_2d_glc_Nx';
Merra2MonthlyMean3DOITable{18,2}='M2TUNXGLC';
Merra2MonthlyMean3DOITable{18,3}='10.5067/7VUPQC736SWX';
Merra2MonthlyMean3DOITable{19,1}='tavgU_3d_cld_Np';
Merra2MonthlyMean3DOITable{19,2}='M2TUNPCLD';
Merra2MonthlyMean3DOITable{19,3}='10.5067/EPW7T5UO0C0N';
Merra2MonthlyMean3DOITable{20,1}='tavgU_3d_mst_Np';
Merra2MonthlyMean3DOITable{20,2}='M2TUNPMST';
Merra2MonthlyMean3DOITable{20,3}='10.5067/ZRSN0JU27DK2';
Merra2MonthlyMean3DOITable{21,1}='tavgU_3d_rad_Np';
Merra2MonthlyMean3DOITable{21,2}='M2TUNPRAD';
Merra2MonthlyMean3DOITable{21,3}='10.5067/H140JMDOWB0Y';
Merra2MonthlyMean3DOITable{22,1}='tavgU_3d_tdt_Np';
Merra2MonthlyMean3DOITable{22,2}='M2TUNPTDT';
Merra2MonthlyMean3DOITable{22,3}='10.5067/QPO9E5TPZ8OF';
Merra2MonthlyMean3DOITable{23,1}='tavgU_3d_trb_Np';
Merra2MonthlyMean3DOITable{23,2}='M2TUNPTRB';
Merra2MonthlyMean3DOITable{23,3}='10.5067/2A99C60CG7WC';
Merra2MonthlyMean3DOITable{24,1}='tavgU_3d_udt_Np';
Merra2MonthlyMean3DOITable{24,2}='M2TUNPUDT';
Merra2MonthlyMean3DOITable{24,3}='10.5067/DO715T7T5PG8';
Merra2MonthlyMean3DOITable{25,1}='tavgU_3d_odt_Np';
Merra2MonthlyMean3DOITable{25,2}='M2TUNPODT';
Merra2MonthlyMean3DOITable{25,3}='10.5067/M8OJ09GZP23E';
Merra2MonthlyMean3DOITable{26,1}='tavgU_3d_qdt_Np';
Merra2MonthlyMean3DOITable{26,2}='M2TUNPQDT';
Merra2MonthlyMean3DOITable{26,3}='10.5067/S8HJXIR0BFTS';
%% Create Aerosol Emissions Tables
AerosolEmissionsHdr =cell(1,4);
AerosolEmissionsTable=cell(11,4);
AerosolEmissionsHdr{1,1}='Aerosol Type';
AerosolEmissionsHdr{1,2}='Source';
AerosolEmissionsHdr{1,3}='Temporal Resolution';
AerosolEmissionsHdr{1,4}='Spatial Resolution';
AerosolEmissionsTable{1,1}='Dust';
AerosolEmissionsTable{1,2}='Wind Driven Emissions';
AerosolEmissionsTable{1,3}='Model';
AerosolEmissionsTable{1,4}='.3125 Deg X 0.25 Deg';
AerosolEmissionsTable{2,1}='Sea Salt';
AerosolEmissionsTable{2,2}='Wind Driven Emissions';
AerosolEmissionsTable{2,3}='Model';
AerosolEmissionsTable{2,4}='Model';
AerosolEmissionsTable{3,1}='Volcanic SO2';
AerosolEmissionsTable{3,2}='AeroCom Phase II';
AerosolEmissionsTable{3,3}='Daily';
AerosolEmissionsTable{3,4}='Point Sources';
AerosolEmissionsTable{4,1}='Biogenic Turpene-(From Trees)';
AerosolEmissionsTable{4,2}='AeroCom Phase II';
AerosolEmissionsTable{4,3}='Monthly Mean';
AerosolEmissionsTable{4,4}='2 Deg x 2.5 Deg';
AerosolEmissionsTable{5,1}='Di-Methyl Sulfide-DMS';
AerosolEmissionsTable{5,2}='Paper By Lana';
AerosolEmissionsTable{5,3}='Monthly Mean';
AerosolEmissionsTable{5,4}='1 Deg x 1 Deg';
AerosolEmissionsTable{6,1}='Biomass Burning';
AerosolEmissionsTable{6,2}='Multiple Papers';
AerosolEmissionsTable{6,3}='Monthly to 2010-Daily Afterwards';
AerosolEmissionsTable{6,4}='.3125 Deg X 0.25 Deg';
AerosolEmissionsTable{7,1}='Anthropogenic SO2';
AerosolEmissionsTable{7,2}='EDGAR ver 4.2';
AerosolEmissionsTable{7,3}='Annually';
AerosolEmissionsTable{7,4}='.1 Deg X 0.1 Deg';
AerosolEmissionsTable{8,1}='Anthropogenic SO4 POM & BC';
AerosolEmissionsTable{8,2}='AeroCom Phase II';
AerosolEmissionsTable{8,3}='Annually';
AerosolEmissionsTable{8,4}='1 Deg X  1 Deg';
AerosolEmissionsTable{9,1}='International Ships SO2';
AerosolEmissionsTable{9,2}='EDGAR ver 4.1';
AerosolEmissionsTable{9,3}='Annually';
AerosolEmissionsTable{9,4}='1 Deg X  1 Deg';
AerosolEmissionsTable{10,1}='International Ships SO4 POM BC';
AerosolEmissionsTable{10,2}='AeroCom Phase II';
AerosolEmissionsTable{10,3}='Annually';
AerosolEmissionsTable{10,4}='1 Deg X  1 Deg';
AerosolEmissionsTable{11,1}='Aircraft SO2';
AerosolEmissionsTable{11,2}='AeroCom Phase II';
AerosolEmissionsTable{11,3}='Monthly';
AerosolEmissionsTable{11,4}='1 Deg X 1.25 Deg 72 Levels';
VariableTableHdr{1,1}='Short Name';
VariableTableHdr{1,2}='DESC';
VariableTableHdr{1,3}='Type';
VariableTableHdr{1,4}='ikind';
VariableTableHdr{1,5}='Note';
VariableTableBC=cell(14,5);
VariableTableOC=cell(1,5);
VariableTableBC{1,1}='BCDP001';
VariableTableBC{1,2}='Black Carbon Dry Deposition Bin001';
VariableTableBC{1,3}='Geo2D';
VariableTableBC{1,4}='1';
VariableTableBC{1,5}='Aerosol Sink';
VariableTableBC{2,1}='BCDP002';
VariableTableBC{2,2}='Black Carbon Dry Deposition Bin002';
VariableTableBC{2,3}='Geo2D';
VariableTableBC{2,4}='2';
VariableTableBC{2,5}='Aerosol Sink';
VariableTableBC{3,1}='BCEM001';
VariableTableBC{3,2}='Black Carbon Emission Bin001';
VariableTableBC{3,3}='Geo2D';
VariableTableBC{3,4}='3';
VariableTableBC{3,5}='Aerosol Source';
VariableTableBC{4,1}='BCEM002';
VariableTableBC{4,2}='Black Carbon Emission Bin002';
VariableTableBC{4,3}='Geo2D';
VariableTableBC{4,4}='4';
VariableTableBC{4,5}='Aerosol Source';
VariableTableBC{5,1}='BCEMAN';
VariableTableBC{5,2}='Black Carbon Antropogenic Emissions';
VariableTableBC{5,3}='Geo2D';
VariableTableBC{5,4}='5';
VariableTableBC{5,5}='Aerosol Source';
VariableTableBC{6,1}='BCEMBB';
VariableTableBC{6,2}='Black Carbon Biogen Emissions';
VariableTableBC{6,3}='Geo2D';
VariableTableBC{6,4}='6';
VariableTableBC{6,5}='Aerosol Source';
VariableTableBC{7,1}='BCEMBF';
VariableTableBC{7,2}='Black Carbon Biofuel Emissions';
VariableTableBC{7,3}='Geo2D';
VariableTableBC{7,4}='7';
VariableTableBC{7,5}='Aerosol Source';
VariableTableBC{8,1}='BCHYPHIL';
VariableTableBC{8,2}='Black Carbon Hydrophobic To Hydrophilic Emissions';
VariableTableBC{8,3}='Geo2D';
VariableTableBC{8,4}='8';
VariableTableBC{8,5}='Chem Process';
VariableTableBC{9,1}='BCSD001';
VariableTableBC{9,2}='Black Carbon Sedimentation Bin 001';
VariableTableBC{9,3}='Geo2D';
VariableTableBC{9,4}='9';
VariableTableBC{9,5}='Aerosol Sink';
VariableTableBC{10,1}='BCSD002';
VariableTableBC{10,2}='Black Carbon Sedimentation Bin 002';
VariableTableBC{10,3}='Geo2D';
VariableTableBC{10,4}='10';
VariableTableBC{10,5}='Aerosol Sink';
VariableTableBC{11,1}='BCSV001';
VariableTableBC{11,2}='Black Carbon Covective Scavenging  Bin 001';
VariableTableBC{11,3}='Geo2D';
VariableTableBC{11,4}='11';
VariableTableBC{11,5}='Aerosol Sink';
VariableTableBC{12,1}='BCSV002';
VariableTableBC{12,2}='Black Carbon Covective Scavenging  Bin 002';
VariableTableBC{12,3}='Geo2D';
VariableTableBC{12,4}='12';
VariableTableBC{12,5}='Aerosol Sink';
VariableTableBC{13,1}='BCWT001';
VariableTableBC{13,2}='Black Carbon Covective Scavenging  Bin 001';
VariableTableBC{13,3}='Geo2D';
VariableTableBC{13,4}='13';
VariableTableBC{13,5}='Aerosol Sink';
VariableTableBC{14,1}='BCWT002';
VariableTableBC{14,2}='Black Carbon Covective Scavenging  Bin 002';
VariableTableBC{14,3}='Geo2D';
VariableTableBC{14,4}='14';
VariableTableBC{14,5}='Aerosol Sink';
VariableTableDustPt1=cell(18,5);
VariableTableDustPt2=cell(10,5);
VariableTableDustPt1{1,1}='DUAERIDX';
VariableTableDustPt1{1,2}='Dust TOMS UV Aerosol Index ';
VariableTableDustPt1{1,3}='Geo2D';
VariableTableDustPt1{1,4}='15';
VariableTableDustPt1{1,5}='N/A';
VariableTableDustPt1{2,1}='DUDP001';
VariableTableDustPt1{2,2}='Dust Dry Deposition Bin 001 ';
VariableTableDustPt1{2,3}='Geo2D';
VariableTableDustPt1{2,4}='16';
VariableTableDustPt1{2,5}='Aerosol Sink';
VariableTableDustPt1{3,1}='DUDP002';
VariableTableDustPt1{3,2}='Dust Dry Deposition Bin 002 ';
VariableTableDustPt1{3,3}='Geo2D';
VariableTableDustPt1{3,4}='17';
VariableTableDustPt1{3,5}='Aerosol Sink';
VariableTableDustPt1{4,1}='DUDP003';
VariableTableDustPt1{4,2}='Dust Dry Deposition Bin 003';
VariableTableDustPt1{4,3}='Geo2D';
VariableTableDustPt1{4,4}='18';
VariableTableDustPt1{4,5}='Aerosol Sink';
VariableTableDustPt1{5,1}='DUDP004';
VariableTableDustPt1{5,2}='Dust Dry Deposition Bin 004';
VariableTableDustPt1{5,3}='Geo2D';
VariableTableDustPt1{5,4}='19';
VariableTableDustPt1{5,5}='Aerosol Sink';
VariableTableDustPt1{6,1}='DUDP005';
VariableTableDustPt1{6,2}='Dust Dry Deposition Bin 005';
VariableTableDustPt1{6,3}='Geo2D';
VariableTableDustPt1{6,4}='20';
VariableTableDustPt1{6,5}='Aerosol Sink';
VariableTableDustPt1{7,1}='DUEM001';
VariableTableDustPt1{7,2}='Dust Emission Bin 001';
VariableTableDustPt1{7,3}='Geo2D';
VariableTableDustPt1{7,4}='21';
VariableTableDustPt1{7,5}='Aerosol Source';
VariableTableDustPt1{8,1}='DUEM002';
VariableTableDustPt1{8,2}='Dust Emission Bin 002';
VariableTableDustPt1{8,3}='Geo2D';
VariableTableDustPt1{8,4}='22';
VariableTableDustPt1{8,5}='Aerosol Source';
VariableTableDustPt1{9,1}='DUEM003';
VariableTableDustPt1{9,2}='Dust Emission Bin 003';
VariableTableDustPt1{9,3}='Geo2D';
VariableTableDustPt1{9,4}='23';
VariableTableDustPt1{9,5}='Aerosol Source';
VariableTableDustPt1{10,1}='DUEM004';
VariableTableDustPt1{10,2}='Dust Emission Bin 004';
VariableTableDustPt1{10,3}='Geo2D';
VariableTableDustPt1{10,4}='24';
VariableTableDustPt1{10,5}='Aerosol Source';
VariableTableDustPt1{11,1}='DUEM005';
VariableTableDustPt1{11,2}='Dust Emission Bin 005';
VariableTableDustPt1{11,3}='Geo2D';
VariableTableDustPt1{11,4}='25';
VariableTableDustPt1{11,5}='Aerosol Source';
VariableTableDustPt1{12,1}='DUEXTTFM';
VariableTableDustPt1{12,2}='Dust Extinction AOT .55 micron';
VariableTableDustPt1{12,3}='Geo2D';
VariableTableDustPt1{12,4}='26';
VariableTableDustPt1{12,5}='N/A';
VariableTableDustPt1{13,1}='DUSCATFM';
VariableTableDustPt1{13,2}='Dust Scattering AOT .55 micron';
VariableTableDustPt1{13,3}='Geo2D';
VariableTableDustPt1{13,4}='27';
VariableTableDustPt1{13,5}='N/A';
VariableTableDustPt1{14,1}='DUSD001';
VariableTableDustPt1{14,2}='Dust Sedimentation Bin 001';
VariableTableDustPt1{14,3}='Geo2D';
VariableTableDustPt1{14,4}='28';
VariableTableDustPt1{14,5}='Aerosol Sink';
VariableTableDustPt1{15,1}='DUSD002';
VariableTableDustPt1{15,2}='Dust Sedimentation Bin 002';
VariableTableDustPt1{15,3}='Geo2D';
VariableTableDustPt1{15,4}='29';
VariableTableDustPt1{15,5}='Aerosol Sink';
VariableTableDustPt1{16,1}='DUSD003';
VariableTableDustPt1{16,2}='Dust Sedimentation Bin 003';
VariableTableDustPt1{16,3}='Geo2D';
VariableTableDustPt1{16,4}='30';
VariableTableDustPt1{16,5}='Aerosol Sink';
VariableTableDustPt1{17,1}='DUSD004';
VariableTableDustPt1{17,2}='Dust Sedimentation Bin 004';
VariableTableDustPt1{17,3}='Geo2D';
VariableTableDustPt1{17,4}='31';
VariableTableDustPt1{17,5}='Aerosol Sink';
VariableTableDustPt1{18,1}='DUSD005';
VariableTableDustPt1{18,2}='Dust Sedimentation Bin 005';
VariableTableDustPt1{18,3}='Geo2D';
VariableTableDustPt1{18,4}='32';
VariableTableDustPt1{18,5}='Aerosol Sink';
VariableTableDustPt2{1,1}='DUSV001';
VariableTableDustPt2{1,2}='Dust Convective Scavenging Bin 001';
VariableTableDustPt2{1,3}='Geo2D';
VariableTableDustPt2{1,4}='33';
VariableTableDustPt2{1,5}='Aerosol Sink';
VariableTableDustPt2{2,1}='DUSV002';
VariableTableDustPt2{2,2}='Dust Convective Scavenging Bin 002';
VariableTableDustPt2{2,3}='Geo2D';
VariableTableDustPt2{2,4}='34';
VariableTableDustPt2{2,5}='Aerosol Sink';
VariableTableDustPt2{3,1}='DUSV003';
VariableTableDustPt2{3,2}='Dust Convective Scavenging Bin 003';
VariableTableDustPt2{3,3}='Geo2D';
VariableTableDustPt2{3,4}='35';
VariableTableDustPt2{3,5}='Aerosol Sink';
VariableTableDustPt2{4,1}='DUSV004';
VariableTableDustPt2{4,2}='Dust Convective Scavenging Bin 004';
VariableTableDustPt2{4,3}='Geo2D';
VariableTableDustPt2{4,4}='36';
VariableTableDustPt2{4,5}='Aerosol Sink';
VariableTableDustPt2{5,1}='DUSV005';
VariableTableDustPt2{5,2}='Dust Convective Scavenging Bin 005';
VariableTableDustPt2{5,3}='Geo2D';
VariableTableDustPt2{5,4}='37';
VariableTableDustPt2{5,5}='Aerosol Sink';
VariableTableDustPt2{6,1}='DUWT001';
VariableTableDustPt2{6,2}='Dust Wet Deposition Bin 001';
VariableTableDustPt2{6,3}='Geo2D';
VariableTableDustPt2{6,4}='38';
VariableTableDustPt2{6,5}='Aerosol Sink';
VariableTableDustPt2{7,1}='DUWT002';
VariableTableDustPt2{7,2}='Dust Wet Deposition Bin 002';
VariableTableDustPt2{7,3}='Geo2D';
VariableTableDustPt2{7,4}='39';
VariableTableDustPt2{7,5}='Aerosol Sink';
VariableTableDustPt2{8,1}='DUWT003';
VariableTableDustPt2{8,2}='Dust Wet Deposition Bin 003';
VariableTableDustPt2{8,3}='Geo2D';
VariableTableDustPt2{8,4}='40';
VariableTableDustPt2{8,5}='Aerosol Sink';
VariableTableDustPt2{9,1}='DUWT004';
VariableTableDustPt2{9,2}='Dust Wet Deposition Bin 004';
VariableTableDustPt2{9,3}='Geo2D';
VariableTableDustPt2{9,4}='41';
VariableTableDustPt2{9,5}='Aerosol Sink';
VariableTableDustPt2{10,1}='DUWT005';
VariableTableDustPt2{10,2}='Dust Wet Deposition Bin 005';
VariableTableDustPt2{10,3}='Geo2D';
VariableTableDustPt2{10,4}='42';
VariableTableDustPt2{10,5}='Aerosol Sink';
VariableTableOC{1,1}='OCDP001';
VariableTableOC{1,2}='Organic Carbon Dry Deposition Bin 001';
VariableTableOC{1,3}='Geo2D';
VariableTableOC{1,4}='45';
VariableTableOC{1,5}='Aerosol Sink';
VariableTableOC{2,1}='OCDP002';
VariableTableOC{2,2}='Organic Carbon Dry Deposition Bin 002';
VariableTableOC{2,3}='Geo2D';
VariableTableOC{2,4}='46';
VariableTableOC{2,5}='Aerosol Sink';
VariableTableOC{3,1}='OCEM001';
VariableTableOC{3,2}='Organic Carbon Emission Bin 001';
VariableTableOC{3,3}='Geo2D';
VariableTableOC{3,4}='47';
VariableTableOC{3,5}='Aerosol Source';
VariableTableOC{4,1}='OCEM003';
VariableTableOC{4,2}='Organic Carbon Emission Bin 003';
VariableTableOC{4,3}='Geo2D';
VariableTableOC{4,4}='48';
VariableTableOC{4,5}='Aerosol Source';
VariableTableOC{5,1}='OCEMAN';
VariableTableOC{5,2}='Organic Carbon Antropogenic Emissions';
VariableTableOC{5,3}='Geo2D';
VariableTableOC{5,4}='49';
VariableTableOC{5,5}='Aerosol Source';
VariableTableOC{6,1}='OCEMBF';
VariableTableOC{6,2}='Organic Carbon Biofuel Emissions';
VariableTableOC{6,3}='Geo2D';
VariableTableOC{6,4}='50';
VariableTableOC{6,5}='Aerosol Source';
VariableTableOC{7,1}='OCEMBF';
VariableTableOC{7,2}='Organic Carbon Biofuel Emissions';
VariableTableOC{7,3}='Geo2D';
VariableTableOC{7,4}='51';
VariableTableOC{7,5}='Aerosol Source';
VariableTableOC{8,1}='OCEMBG';
VariableTableOC{8,2}='Organic Carbon Biogenic Emissions';
VariableTableOC{8,3}='Geo2D';
VariableTableOC{8,4}='52';
VariableTableOC{8,5}='Aerosol Source';
VariableTableOC{9,1}='OCHYPHIL';
VariableTableOC{9,2}='Organic Carbon Hydrophobic to Hydrophilic';
VariableTableOC{9,3}='Geo2D';
VariableTableOC{9,4}='53';
VariableTableOC{9,5}='Aerosol Sink';
VariableTableOC{10,1}='OCSD001';
VariableTableOC{10,2}='Organic Carbon Sedimentation Bin 001';
VariableTableOC{10,3}='Geo2D';
VariableTableOC{10,4}='54';
VariableTableOC{10,5}='Aerosol Sink';
VariableTableOC{11,1}='OCSD002';
VariableTableOC{11,2}='Organic Carbon Sedimentation Bin 002';
VariableTableOC{11,3}='Geo2D';
VariableTableOC{11,4}='55';
VariableTableOC{11,5}='Aerosol Sink';
VariableTableOC{12,1}='OCSV001';
VariableTableOC{12,2}='Organic Carbon Convective Scavenging Bin 001';
VariableTableOC{12,3}='Geo2D';
VariableTableOC{12,4}='56';
VariableTableOC{12,5}='Aerosol Sink';
VariableTableOC{13,1}='OCSV002';
VariableTableOC{13,2}='Organic Carbon Convective Scavenging Bin 002';
VariableTableOC{13,3}='Geo2D';
VariableTableOC{13,4}='57';
VariableTableOC{13,5}='Aerosol Sink';
VariableTableOC{14,1}='OCWT001';
VariableTableOC{14,2}='Organic Carbon Wet Deposition Bin 001';
VariableTableOC{14,3}='Geo2D';
VariableTableOC{14,4}='58';
VariableTableOC{14,5}='Aerosol Sink';
VariableTableOC{15,1}='OCWT002';
VariableTableOC{15,2}='Organic Carbon Wet Deposition Bin 002';
VariableTableOC{15,3}='Geo2D';
VariableTableOC{15,4}='59';
VariableTableOC{15,5}='Aerosol Sink';
VariableTableSulfatesPt1{1,1}='SO2EMAN';
VariableTableSulfatesPt1{1,2}='SO2 Anthropogenic Emissions';
VariableTableSulfatesPt1{1,3}='Geo2D';
VariableTableSulfatesPt1{1,4}='60';
VariableTableSulfatesPt1{1,5}='Aerosol Source';
VariableTableSulfatesPt1{2,1}='SO2EMBB';
VariableTableSulfatesPt1{2,2}='SO2 Biomass Burning Emissions';
VariableTableSulfatesPt1{2,3}='Geo2D';
VariableTableSulfatesPt1{2,4}='61';
VariableTableSulfatesPt1{2,5}='Aerosol Source';
VariableTableSulfatesPt1{3,1}='SO2EMVE';
VariableTableSulfatesPt1{3,2}='SO2 Volcanic Explosive Emissions';
VariableTableSulfatesPt1{3,3}='Geo2D';
VariableTableSulfatesPt1{3,4}='62';
VariableTableSulfatesPt1{3,5}='Aerosol Source';
VariableTableSulfatesPt1{4,1}='SO2EMVN';
VariableTableSulfatesPt1{4,2}='SO2 Volcanic Non Explosive Emissions';
VariableTableSulfatesPt1{4,3}='Geo2D';
VariableTableSulfatesPt1{4,4}='63';
VariableTableSulfatesPt1{4,5}='Aerosol Source';
VariableTableSulfatesPt1{5,1}='SO4EMAN';
VariableTableSulfatesPt1{5,2}='SO4 Antropogenic Emissions';
VariableTableSulfatesPt1{5,3}='Geo2D';
VariableTableSulfatesPt1{5,4}='64';
VariableTableSulfatesPt1{5,5}='Aerosol Source';
VariableTableSulfatesPt1{6,1}='SUDP001';
VariableTableSulfatesPt1{6,2}='Sulfate Dry Deposition Bin 001';
VariableTableSulfatesPt1{6,3}='Geo2D';
VariableTableSulfatesPt1{6,4}='93';
VariableTableSulfatesPt1{6,5}='Aerosol Sink';
VariableTableSulfatesPt1{7,1}='SUDP002';
VariableTableSulfatesPt1{7,2}='Sulfate Dry Deposition Bin 002';
VariableTableSulfatesPt1{7,3}='Geo2D';
VariableTableSulfatesPt1{7,4}='94';
VariableTableSulfatesPt1{7,5}='Aerosol Sink';
VariableTableSulfatesPt1{8,1}='SUDP003';
VariableTableSulfatesPt1{8,2}='Sulfate Dry Deposition Bin 003';
VariableTableSulfatesPt1{8,3}='Geo2D';
VariableTableSulfatesPt1{8,4}='95';
VariableTableSulfatesPt1{8,5}='Aerosol Sink';
VariableTableSulfatesPt1{9,1}='SUDP004';
VariableTableSulfatesPt1{9,2}='Sulfate Dry Deposition Bin 004';
VariableTableSulfatesPt1{9,3}='Geo2D';
VariableTableSulfatesPt1{9,4}='96';
VariableTableSulfatesPt1{9,5}='Aerosol Sink';
VariableTableSulfatesPt1{10,1}='SUEM001';
VariableTableSulfatesPt1{10,2}='Sulfate Emission Bin 001';
VariableTableSulfatesPt1{10,3}='Geo2D';
VariableTableSulfatesPt1{10,4}='97';
VariableTableSulfatesPt1{10,5}='Aerosol Sink';
VariableTableSulfatesPt1{11,1}='SUEM002';
VariableTableSulfatesPt1{11,2}='Sulfate Emission Bin 002';
VariableTableSulfatesPt1{11,3}='Geo2D';
VariableTableSulfatesPt1{11,4}='98';
VariableTableSulfatesPt1{11,5}='Aerosol Sink';
VariableTableSulfatesPt1{12,1}='SUEM003';
VariableTableSulfatesPt1{12,2}='Sulfate Emission Bin 003';
VariableTableSulfatesPt1{12,3}='Geo2D';
VariableTableSulfatesPt1{12,4}='99';
VariableTableSulfatesPt1{12,5}='Aerosol Sink';
VariableTableSulfatesPt1{13,1}='SUEM004';
VariableTableSulfatesPt1{13,2}='Sulfate Emission Bin 004';
VariableTableSulfatesPt1{13,3}='Geo2D';
VariableTableSulfatesPt1{13,4}='100';
VariableTableSulfatesPt1{13,5}='Aerosol Sink';
VariableTableSulfatesPt1{14,1}='SUPMSA';
VariableTableSulfatesPt1{14,2}='MSA Prod From DMS Oxidation';
VariableTableSulfatesPt1{14,3}='Geo2D';
VariableTableSulfatesPt1{14,4}='101';
VariableTableSulfatesPt1{14,5}='Chem Process';
VariableTableSulfatesPt1{15,1}='SUPSO2';
VariableTableSulfatesPt1{15,2}='SO2 Prod From DMS Oxidation';
VariableTableSulfatesPt1{15,3}='Geo2D';
VariableTableSulfatesPt1{15,4}='102';
VariableTableSulfatesPt1{15,5}='Chem Process';
VariableTableSulfatesPt1{16,1}='SUPSO4AQ';
VariableTableSulfatesPt1{16,2}='SO4 Prod From Aqueous S02 Oxidation';
VariableTableSulfatesPt1{16,3}='Geo2D';
VariableTableSulfatesPt1{16,4}='103';
VariableTableSulfatesPt1{16,5}='Chem Process';
VariableTableSulfatesPt1{17,1}='SUPSO4G';
VariableTableSulfatesPt1{17,2}='SO4 Prod From Gaseous SO2 Oxidation';
VariableTableSulfatesPt1{17,3}='Geo2D';
VariableTableSulfatesPt1{17,4}='104';
VariableTableSulfatesPt1{17,5}='Chem Process';
VariableTableSulfatesPt1{18,1}='SUPSO4WT';
VariableTableSulfatesPt1{18,2}='SO4 Prod From Gaseous SO2 Oxidation wet';
VariableTableSulfatesPt1{18,3}='Geo2D';
VariableTableSulfatesPt1{18,4}='105';
VariableTableSulfatesPt1{18,5}='Chem Process';
VariableTableSulfatesPt2=cell(1,1);
VariableTableSulfatesPt2{1,1}='SUSD001';
VariableTableSulfatesPt2{1,2}='Sulfate Settling Bin 001';
VariableTableSulfatesPt2{1,3}='Geo2D';
VariableTableSulfatesPt2{1,4}='106';
VariableTableSulfatesPt2{1,5}='Sink';
VariableTableSulfatesPt2{2,1}='SUSD002';
VariableTableSulfatesPt2{2,2}='Sulfate Settling Bin 002';
VariableTableSulfatesPt2{2,3}='Geo2D';
VariableTableSulfatesPt2{2,4}='107';
VariableTableSulfatesPt2{2,5}='Sink';
VariableTableSulfatesPt2{3,1}='SUSD003';
VariableTableSulfatesPt2{3,2}='Sulfate Settling Bin 003';
VariableTableSulfatesPt2{3,3}='Geo2D';
VariableTableSulfatesPt2{3,4}='108';
VariableTableSulfatesPt2{3,5}='Sink';
VariableTableSulfatesPt2{4,1}='SUSD004';
VariableTableSulfatesPt2{4,2}='Sulfate Settling Bin 004';
VariableTableSulfatesPt2{4,3}='Geo2D';
VariableTableSulfatesPt2{4,4}='109';
VariableTableSulfatesPt2{4,5}='Sink';
VariableTableSulfatesPt2{5,1}='SUSV001';
VariableTableSulfatesPt2{5,2}='Sulfate Convective Scavenging Bin 001';
VariableTableSulfatesPt2{5,3}='Geo2D';
VariableTableSulfatesPt2{5,4}='110';
VariableTableSulfatesPt2{5,5}='Sink';
VariableTableSulfatesPt2{6,1}='SUSV002';
VariableTableSulfatesPt2{6,2}='Sulfate Convective Scavenging Bin 002';
VariableTableSulfatesPt2{6,3}='Geo2D';
VariableTableSulfatesPt2{6,4}='111';
VariableTableSulfatesPt2{6,5}='Sink';
VariableTableSulfatesPt2{7,1}='SUSV003';
VariableTableSulfatesPt2{7,2}='Sulfate Convective Scavenging Bin 003';
VariableTableSulfatesPt2{7,3}='Geo2D';
VariableTableSulfatesPt2{7,4}='112';
VariableTableSulfatesPt2{7,5}='Sink';
VariableTableSulfatesPt2{8,1}='SUSV004';
VariableTableSulfatesPt2{8,2}='Sulfate Convective Scavenging Bin 004';
VariableTableSulfatesPt2{8,3}='Geo2D';
VariableTableSulfatesPt2{8,4}='113';
VariableTableSulfatesPt2{8,5}='Sink';
VariableTableSulfatesPt2{9,1}='SUWT001';
VariableTableSulfatesPt2{9,2}='Sulfate Wet Deposition Bin 001';
VariableTableSulfatesPt2{9,3}='Geo2D';
VariableTableSulfatesPt2{9,4}='114';
VariableTableSulfatesPt2{9,5}='Sink';
VariableTableSulfatesPt2{10,1}='SUWT002';
VariableTableSulfatesPt2{10,2}='Sulfate Wet Deposition Bin 002';
VariableTableSulfatesPt2{10,3}='Geo2D';
VariableTableSulfatesPt2{10,4}='115';
VariableTableSulfatesPt2{10,5}='Sink';
VariableTableSulfatesPt2{11,1}='SUWT003';
VariableTableSulfatesPt2{11,2}='Sulfate Wet Deposition Bin 003';
VariableTableSulfatesPt2{11,3}='Geo2D';
VariableTableSulfatesPt2{11,4}='116';
VariableTableSulfatesPt2{11,5}='Sink';
VariableTableSulfatesPt2{12,1}='SUWT003';
VariableTableSulfatesPt2{12,2}='Sulfate Wet Deposition Bin 004';
VariableTableSulfatesPt2{12,3}='Geo2D';
VariableTableSulfatesPt2{12,4}='117';
VariableTableSulfatesPt2{12,5}='Sink';

% Set some flags

%iCreatePDFReport=1;
JpegCounter=0;


%% Create New Chapter with Information Specific to Aerosol Diagnostics
    chapter = Chapter("Title", "Merra-2 Aerosol Diagnostic Products");
    chapter.Layout.Landscape = true;
    add(chapter,Section('General Information'));
    br = PageBreak();
%    add(chapter,br);
    parastr1='This section is designed to provide some top-level on the new aerosol assimilation process that is included in Merra 2.';
    parastr2='One of the key differences between the original Merra program and Merra 2 is the widespread availability of satellte observations.'; 
    parastr3=' This program started in 1980 and is run by the NASA Global Model and Assimilation Office (GMAO).';
    parastr4=' Another significant change is the incoporation of a new model called GOCART into the Goddard Earth Observing System Model or GOES-5 .';
    parastr5=' The GOCART model simulates organic and black carbon,dust and sulfate aerosols';
    parastr9=strcat(parastr1,parastr2,parastr3,parastr4,parastr5);
    p1 = Paragraph(parastr9);
    p1.Style = {OuterMargin("0pt", "0pt","10pt","10pt")};
    add(chapter,p1);
    parastr31='The GOCART model considers the sources,sinks and chemistry of the major aeosol components mentioned above.';
    parastr32=' All of the different aerosol components are treated as being externally mixed in the atmosphere.';
    parastr33=' Aerosol particle sizes are grouped in bins and the data for the different sizes are explixitly saved as such.'; 
    parastr34=' For example,dust and sea salt aerosols are grouped in 5 non interfering bins. Carbon particles have generally two important bin sizes.';
    parastr35=' In a later section,the specific file to be used when Option 2 is selected by this script will be detailed.';
    parastr36=' This file,has 117 2D data variables reported on the standard grid.';
    parastr37=' A large nummber of variables are required as the file is mostly reporting on the sources,sinks and chemistry of each of the aerosol types.';
    parastr39=strcat(parastr31,parastr32,parastr33,parastr34,parastr35,parastr36,parastr37);
    p4 = Paragraph(parastr39);
    p4.Style = {OuterMargin("0pt", "0pt","10pt","10pt")};
    add(chapter,p4);
    parastr11='GEOS-5 is an integrated series of models that employ a common framework called the Earth System Modelling Framework (ESMF).';
    parastr12=' The acronomy GEOS stands fro Goddard Earth Observering System.';
    parastr13='The GEOS-5 Data Assimilation System integrated the a climate modelling system with a gridpoint system interpolation routine.'; 
    parastr14=' Overall the purpose is to facilitae the development of climate models and predictions.';
    parastr15=' The data required to model atsmospheric event is very large-in order to have practical file sizes a uniform grid has been created to model data.';
    parastr16=' Assimilation of data occurs on a grid of points with about .5 deg in latitude and longitude.';
    parastr17=' This data is reported on a fixed grid of .625 deg in longitude and .5 degrees in latitude with 72 pressure levels.';
    parastr18=' Typically the data is reported 8 synoptic times a day (0/3/6/9/12/15/18/21 hrs each day';
    parastr18a=' Files are also available for monthly or diurnal averages.';
    parastr2=strcat(parastr11,parastr12,parastr13,parastr14,parastr15,parastr16,parastr17,parastr18,parastr18a);
    p2 = Paragraph(parastr2);
    p2.Style = {OuterMargin("0pt", "0pt","10pt","10pt")};
    add(chapter,p2);

% Show an Example of Sea Salt Emission
    eval(['cd ' govjpegpath(1:length(govjpegpath)-1)]);
    imdata = imread('SeaSaltEmissionBin04-20170830.jpg');
    [nhigh,nwid,~]=size(imdata);
    nhigh2=floor(nhigh/2.1);
    nwid2=floor(nwid/2.1);
    image = mlreportgen.report.FormalImage();
    image.Image = which('SeaSaltEmissionBin04-20170830.jpg');
    text = Text('Example Sea Salt Emission in 2017');
    text.Color = 'red';
    image.Caption = text;
    heightstr=strcat(num2str(nhigh2),'px');
    widthstr=strcat(num2str(nwid2),'px');
    image.Height = heightstr;
    image.Width = widthstr;
    image.ScaleToFit=0;
    image1=image;
    add(chapter,image); 
    parastr51='The figure above was generated using the software tool Panoply which is freely available of the EarthData website.';
    parastr52=' The map display which is used is standard and is based on plotting the SeaSalt Emission data on a 576 x 361 grid for a single time slice.';
    parastr53=' Most of the gridded data provided in this dataset is in units of kg/m^2/sec and is plotted in these units in Panoply.';
    parastr54=' In order to have more sensible numbers the Matlab software convers this to femtogm/m^2/sec.';
    parastr55=' The reader should note that this is for a single (1 hr) time slice at 6 hrs GMT for Bin 04.';
    parastr56=' For the Sea Salt aerosols bin size 04 corresponds to particles in the 1.5 to 5 micron range.';
    parastr57=' The stongest emission is occuring south of the Japanese islands.';
    parastr59=strcat(parastr51,parastr52,parastr53,parastr54,parastr55,parastr56,parastr57);
    p5 = Paragraph(parastr59);
    p5.Style = {OuterMargin("0pt", "0pt","50pt","10pt")};
    add(chapter,p5);
    add(chapter,br);
  % Show an Example of Dust Emission Emission in Bin 04
    eval(['cd ' govjpegpath(1:length(govjpegpath)-1)]);
    imdata = imread('DustEmissionBin04-20170830.jpg');
    [nhigh,nwid,~]=size(imdata);
    nhigh2=floor(nhigh/2.1);
    nwid2=floor(nwid/2.1);
    image = mlreportgen.report.FormalImage();
    image.Image = which('DustEmissionBin04-20170830.jpg');
    text = Text('Example Dust Emission in 2017');
    text.Color = 'red';
    image.Caption = text;
    heightstr=strcat(num2str(nhigh2),'px');
    widthstr=strcat(num2str(nwid2),'px');
    image.Height = heightstr;
    image.Width = widthstr;
    image.ScaleToFit=0;
    image2=image;
    add(chapter,image); 
    parastr61='The comments for the previous figure most apply in this case for Dust Emission in Bin 04 on the same date and time.';
    parastr62=' Bin sizes for Dust are different for the Sea Salt so in this case Bin04 concerns particles of 0.6 to 1.0 microns.';
    parastr63=' Not surprisongly,most of the dust is concentrated at or near the deserts of Africa.';
    parastr69=strcat(parastr61,parastr62,parastr63);
    p7 = Paragraph(parastr69);
    p7.Style = {OuterMargin("0pt", "0pt","10pt","10pt")};
    add(chapter,p7);
    add(chapter,br);

% Show the Aerosol Emissions As a Table
    T1=[AerosolEmissionsHdr;AerosolEmissionsTable];
    tbl1=Table(T1);
    tbl1.Style = [tbl1.Style {Border('solid','black','3px')}];
    tbl1.TableEntriesHAlign = 'center';
    tbl1.HAlign='center';
    tbl1.ColSep = 'single';
    tbl1.RowSep = 'single';
    r = row(tbl1,1);
    r.Style = [r.Style {Color('red'),Bold(true)}];
    bt1 = BaseTable(tbl1);
    tabletitle = Text('Aerosol Emissions Table');
    tabletitle.Bold = false;
    bt1.Title = tabletitle;
    bt1.TableWidth="7in";
    add(chapter,bt1);
    parastr1301='The table above provides some addtional details on atmospheric aerosol emission.';
    parastr1302=' Column 1 specifies the aerosol component while columns 3 and 4 provide data on temporal and spatial resoulution.';
    parastr1303=' Column 3 provides a reference model some cases.';
    parastr1309=strcat(parastr1301,parastr1302,1303);
    p39= Paragraph(parastr1309);
    p39.Style = {OuterMargin("0pt", "0pt","10pt","10pt")};
    add(chapter,p39);
    add(chapter,br);
    

%% Start a new section that describes the specific data set used
    add(chapter,Section('Aerosol Diagnostics Information'));
    parastr201='This section describes the specific data files used to perform the Aerosol diagnostics.';
    parastr202=' All the files in this group cover a 1 day time period with 24 time slices at hourly frequency.'; 
    parastr203=' These are relatively large files at about 756 MBytes per file.';
    parastr204=' Below this paragraph is a screenshot of the landing page for this data set which provides some very useful information .';
    parastr205=' At the very top of this landing page the text reveals that this is hourly time averaged data.';
    parastr206=' In addition this is 2D data,namely lat and lon values specified by the grid and the adg text reveals this is an aerosol diagnostic file.';
    parastr207=' Spatial and temporal resolution data is provided at the very bottom of the page.';
    parastr21=strcat(parastr201,parastr202,parastr203,parastr204,parastr205,parastr206,parastr207);
    p21 = Paragraph(parastr21);
    p21.Style = {OuterMargin("0pt", "0pt","10pt","10pt")};
    add(chapter,p21);
    %% Add a Jpeg of the Landing page
    eval(['cd ' govjpegpath(1:length(govjpegpath)-1)]);
    imdata = imread('AerosolDiagnosticsLandingPage.jpg');
    [nhigh,nwid,~]=size(imdata);
    nhigh2=floor(nhigh/1.2);
    nwid2=floor(nwid/1.2);
    image = mlreportgen.report.FormalImage();
    image.Image = which('AerosolDiagnosticsLandingPage.jpg');
    text = Text('Basic Info On Aerosol Diagnostics File');
    text.Color = 'red';
    image.Caption = text;
    heightstr=strcat(num2str(nhigh2),'px');
    widthstr=strcat(num2str(nwid2),'px');
    image.Height = heightstr;
    image.Width = widthstr;
    image.ScaleToFit=0;
    add(chapter,image); 
    parastr221='The figure above is a screen grab of the Aerosol Diagnostics File Landing Page.';
    parastr222=' Page URL is https://disc.gsfc.nasa.gov/api/jobs/results/64bd4588dc82ce856f8360d9.';
    parastr223=' The most important function of the landing page is to allow the user to download the desird datasets.';
    parastr224=' A series of images will display to techniques for doing this.';
    parastr22=strcat(parastr221,parastr222,parastr223,parastr224);
    p22 = Paragraph(parastr22);
    p22.Style = {OuterMargin("0pt", "0pt","10pt","10pt")};
    add(chapter,p22);
    add(chapter,br);
%% Add a Jpeg showing the File Dialog Box
    eval(['cd ' govjpegpath(1:length(govjpegpath)-1)]);
    imdata = imread('DataAccessDialogBox.jpg');
    [nhigh,nwid,~]=size(imdata);
    nhigh2=floor(nhigh/1.2);
    nwid2=floor(nwid/1.2);
    image = mlreportgen.report.FormalImage();
    image.Image = which('DataAccessDialogBox.jpg');
    text = Text('File selection For Download');
    text.Color = 'red';
    image.Caption = text;
    heightstr=strcat(num2str(nhigh2),'px');
    widthstr=strcat(num2str(nwid2),'px');
    image.Height = heightstr;
    image.Width = widthstr;
    image.ScaleToFit=0;
    add(chapter,image); 
    parastr231='The dialog box to select files for download is shown in this graphic.';
    parastr232=' It is actually on the right side of the landing page but was cropped out in the landing page image for clarity.';
    parastr233=' With this dialog the user can select which files can be downloaded and the method to be used.';
    parastr234=' In the example case shown the entire file is downloaded but the user can download a much smaller version of the file with fewer variables.';
    parastr235=' To get the process started the user can click on the very bottom of the box where is labelled="subset get data".';
    parastr23=strcat(parastr231,parastr232,parastr233,parastr234,parastr235);
    p23 = Paragraph(parastr23);
    p23.Style = {OuterMargin("0pt", "0pt","10pt","50pt")};
    add(chapter,p23);
    add(chapter,br);

   %% Add a Jpeg showing File Selection
    eval(['cd ' govjpegpath(1:length(govjpegpath)-1)]);
    imdata = imread('DataAccessPt1.jpg');
    [nhigh,nwid,~]=size(imdata);
    nhigh2=floor(nhigh/1.2);
    nwid2=floor(nwid/1.2);
    image = mlreportgen.report.FormalImage();
    image.Image = which('DataAccessPt1.jpg');
    text = Text('Initial File Selection');
    text.Color = 'red';
    image.Caption = text;
    heightstr=strcat(num2str(nhigh2),'px');
    widthstr=strcat(num2str(nwid2),'px');
    image.Height = heightstr;
    image.Width = widthstr;
    image.ScaleToFit=0;
    add(chapter,image); 
    parastr241='After pressing the subset get data tab in from the previous image the next screen appears.';
    parastr242=' A calender like dialog appears and the user selects 31 files for the month of Jul 2022.';
    parastr243=' Before the download can begin the user must press the green get data button on the lower right side of the box.';
    parastr244=' This example shows that Jul 2022 was selected but in the next chart the user changed this to Aug 2022.';
    parastr245=' This process can be time consuming so it is good practice to select no more than 1 or 2 months worth of data at a time.';
    parastr24=strcat(parastr241,parastr242,parastr243,parastr244,parastr245);
    p24 = Paragraph(parastr24);
    p24.Style = {OuterMargin("0pt", "0pt","10pt","10pt")};
    add(chapter,p24);
    add(chapter,br);
 %% Add a Jpeg showing File Selection for Jul 2022
    eval(['cd ' govjpegpath(1:length(govjpegpath)-1)]);
    imdata = imread('DataAccessPt2.jpg');
    [nhigh,nwid,~]=size(imdata);
    nhigh2=floor(nhigh/1.2);
    nwid2=floor(nwid/1.2);
    image = mlreportgen.report.FormalImage();
    image.Image = which('DataAccessPt2.jpg');
    text = Text('Initial File Selection');
    text.Color = 'red';
    image.Caption = text;
    heightstr=strcat(num2str(nhigh2),'px');
    widthstr=strcat(num2str(nwid2),'px');
    image.Height = heightstr;
    image.Width = widthstr;
    image.ScaleToFit=0;
    add(chapter,image); 
    parastr251='After pressing the subset get data tab in from the previous image the next screen appears.';
    parastr252=' A calender like dialog appears and this time the user selects 31 files for the month of Aug 2022.';
    parastr25=strcat(parastr251,parastr252);
    p25 = Paragraph(parastr25);
    p25.Style = {OuterMargin("0pt", "0pt","10pt","10pt")};
    add(chapter,p25);
    add(chapter,br);
  %% Add a Jpeg showing Manual File Download
    eval(['cd ' govjpegpath(1:length(govjpegpath)-1)]);
    imdata = imread('DataAccessPt3.jpg');
    [nhigh,nwid,~]=size(imdata);
    nhigh2=floor(nhigh/1.2);
    nwid2=floor(nwid/1.2);
    image = mlreportgen.report.FormalImage();
    image.Image = which('DataAccessPt3.jpg');
    text = Text('HTTP Manual Download');
    text.Color = 'red';
    image.Caption = text;
    heightstr=strcat(num2str(nhigh2),'px');
    widthstr=strcat(num2str(nwid2),'px');
    image.Height = heightstr;
    image.Width = widthstr;
    image.ScaleToFit=0;
    add(chapter,image); 
    parastr261='A user can manually download the selected files one at a time using manual pointing and clicking.';
    parastr262=' Multiple files can be downloaded if the user clicks one file at a time after a few seconds wait.';
    parastr263=' Selecting more than 10 files for download at one time starts to increase the time required so it is best to do this in 3-6 batches.';
    parastr264=' This method works although it requires more user intervention-time to download 30 files in this fashion will be aboue 1 hour.';
    parastr26=strcat(parastr261,parastr262,parastr263,parastr264);
    p26 = Paragraph(parastr26);
    p26.Style = {OuterMargin("0pt", "0pt","10pt","10pt")};
    add(chapter,p26);
    add(chapter,br);
  %% Add a Jpeg showing Wget File Download
    eval(['cd ' govjpegpath(1:length(govjpegpath)-1)]);
    imdata = imread('DataAccessPt4.jpg');
    [nhigh,nwid,~]=size(imdata);
    nhigh2=floor(nhigh/1.2);
    nwid2=floor(nwid/1.2);
    image = mlreportgen.report.FormalImage();
    image.Image = which('DataAccessPt4.jpg');
    text = Text('HTTP Scripted Download');
    text.Color = 'red';
    image.Caption = text;
    heightstr=strcat(num2str(nhigh2),'px');
    widthstr=strcat(num2str(nwid2),'px');
    image.Height = heightstr;
    image.Width = widthstr;
    image.ScaleToFit=0;
    add(chapter,image); 
    parastr271='Another convenient method to download files it to use the wget function from the command line.';
    parastr272=' The chart above is essential the one shown in the preceeding graphic except the users cursor is set to hover over the download instructions .';
    parastr273=' If the user selects option 2 a list of url links will be generated in a simple text file.';
    parastr274=' This list can be inserted into a wget command line and the download will proceed through the list of links one by one.';
    parastr275=' All the user need do is save this into a simple text file and ingest into into wget.';
    parastr27=strcat(parastr271,parastr272,parastr273,parastr274,parastr275);
    p27 = Paragraph(parastr27);
    p27.Style = {OuterMargin("0pt", "0pt","10pt","10pt")};
    add(chapter,p27);
    add(chapter,br);
 %% Add a Jpeg showing Wget URL links file
    eval(['cd ' govjpegpath(1:length(govjpegpath)-1)]);
    imdata = imread('DataAccessLinks.jpg');
    [nhigh,nwid,~]=size(imdata);
    nhigh2=floor(nhigh/1.2);
    nwid2=floor(nwid/1.2);
    image = mlreportgen.report.FormalImage();
    image.Image = which('DataAccessLinks.jpg');
    text = Text('URL File Links');
    text.Color = 'red';
    image.Caption = text;
    heightstr=strcat(num2str(nhigh2),'px');
    widthstr=strcat(num2str(nwid2),'px');
    image.Height = heightstr;
    image.Width = widthstr;
    image.ScaleToFit=0;
    add(chapter,image); 
    parastr281='This graphic shows the list of file links that are created when option 2 is selected.';
    parastr282=' The readme file is unneeded and can be edited out-just save this file with a simple name and the wget command will be executed in the command line .';
    parastr28=strcat(parastr281,parastr282);
    p28 = Paragraph(parastr28);
    p28.Style = {OuterMargin("0pt", "0pt","10pt","10pt")};
    add(chapter,p28);
    add(chapter,br);
%% Add a Jpeg showing Wget command to download the data
    eval(['cd ' govjpegpath(1:length(govjpegpath)-1)]);
    imdata = imread('wget_example.jpg');
    [nhigh,nwid,~]=size(imdata);
    nhigh2=floor(nhigh/1.2);
    nwid2=floor(nwid/1.2);
    image = mlreportgen.report.FormalImage();
    image.Image = which('wget_example.jpg');
    text = Text('Download with wget');
    text.Color = 'red';
    image.Caption = text;
    heightstr=strcat(num2str(nhigh2),'px');
    widthstr=strcat(num2str(nwid2),'px');
    image.Height = heightstr;
    image.Width = widthstr;
    image.ScaleToFit=0;
    add(chapter,image); 
    parastr291='This is a screen shot in the command line using the wget command to download the data.';
    parastr292=' The command fits on 1 line-wget is called the http protocal will be used the user login credentials are read in .';
    parastr293=' Once this is accomplished the file MT21NXADG_Aug2022_.txt is read in to process each download link one at a time.';
    parastr29=strcat(parastr291,parastr292,parastr293);
    p29 = Paragraph(parastr29);
    p29.Style = {OuterMargin("0pt", "0pt","10pt","10pt")};
    add(chapter,p29);
    add(chapter,br);

%% Add another section to Chapter 2 on Aerosol Diagnostic Files
    add(chapter,Section('Merra-2 Aerosol Diagnostic Files'));
    parastr51='This section will provide some details on the Aerosol Diagnostic Files.';
    parastr52=' A typical file name in this series is "Merra2_100.tavg1_2d_adg_Nx.19800101".';
    parastr53=' The 100 series means that this was in the time period of the first data assimulation and later files have numbers up to 400.'; 
    parastr54=' Tavg1 is a key that tells the user is is time averaged data at 1 hr intervals.';
    parastr55=' The key 2d means that this data is on a 2 d lat/lon grid and adg means that this is an aerosol diagnostic file.';
    parastr56=' Nx is another key word that means it is native format 2 d data.';
    parastr57=' The final 8 digits states that the file is for 1980 month 1 day or Jan1 1980.';
    parastr58=' The extentsion is netCDF which stands for net Common Data Format which many datasets are written in-this is similar to HDF.';
    parastr6=strcat(parastr51,parastr52,parastr53,parastr54,parastr55,parastr56,parastr57,parastr58);
    p6 = Paragraph(parastr6);
    p6.Style = {OuterMargin("0pt", "0pt","10pt","10pt")};
    add(chapter,p6);
    parastr61='This particular set of files is quite large averages about 780 MB in size.';
    parastr62=' Aerosol diagnostic files are so large for two reasons, the large number of variables stored on it is the first .';
    parastr63=' Secondly there are 117 georeferenced variable with each variable having a dimension of 576 x 361 x 24.'; 
    parastr64=' The longitude is stored in 576 grid points and the latitude in 361 points and there are 24 time slices in it.';
    parastr65=' The corresponding latitude limits of +/-90 deg are mapped into 361 points.';
    parastr66=' In practice this means that the spatial resolution is 0.5 x 0.625 deg.';
    parastr67=' As such,the grids are equally size in angular measure but not in linear extent.';
    parastr7=strcat(parastr61,parastr62,parastr63,parastr64,parastr65,parastr66,parastr67);
    p7 = Paragraph(parastr7);
    p7.Style = {OuterMargin("0pt", "0pt","20pt","10pt")};
    add(chapter,p7);
% Add Table showing Black Carbon Variables
    add(chapter,br);
    T2=[VariableTableHdr;VariableTableBC];
    tbl2=Table(T2);
    tbl2.Style = [tbl2.Style {Border('solid','black','3px')}];
    tbl2.TableEntriesHAlign = 'center';
    tbl2.HAlign='center';
    tbl2.ColSep = 'single';
    tbl2.RowSep = 'single';
    r = row(tbl2,1);
    r.Style = [r.Style {Color('red'),Bold(true)}];
    bt2 = BaseTable(tbl2);
    tabletitle = Text('Variable List For Black Carbon');
    tabletitle.Bold = false;
    bt2.Title = tabletitle;
    bt2.TableWidth="7in";
    add(chapter,bt2);
    parastr201='The table above shows the 14 variables that are stored in the aerosol diagnostic file that are related to Black Carbon.';
    parastr202=' Column 1 shows he short name for each variable while column 2 provides a brief description of the variable.';
    parastr203=' The structure of the variable is Geo2d means that it is a 2 dimension georeference variable on the standard Merra2 grid.';
    parastr204=' All the variables are plotted will be plotted using the same subroutine,ikind is the tag number used by the plot routine.';
    parastr205=' The final column details whether the variable is a source,or sink for that aerosol species or a chemical process.';
    parastr206=' Black carbon is he dominant type of light absorbing particulate matter in the atmosphere-it has a life time of about 2 weeks.';
    parastr207=' As such this aerosol can absorb visible and IR light and thus heat the atmosphere and darken surfaces.';
    parastr209=strcat(parastr201,parastr202,parastr203,parastr204,parastr205,parastr206,parastr207);
    p21= Paragraph(parastr209);
    p21.Style = {OuterMargin("0pt", "0pt","20pt","10pt")};
    add(chapter,p21);
% Add Table showing Dust Aerosol Variables Pt1
    add(chapter,br);
    T3=[VariableTableHdr;VariableTableDustPt1];
    tbl3=Table(T3);
    tbl3.Style = [tbl3.Style {Border('solid','black','3px')}];
    tbl3.TableEntriesHAlign = 'center';
    tbl3.HAlign='center';
    tbl3.ColSep = 'single';
    tbl3.RowSep = 'single';
    r = row(tbl3,1);
    r.Style = [r.Style {Color('red'),Bold(true)}];
    bt3 = BaseTable(tbl3);
    tabletitle = Text('Variable List For Dust Part 1');
    tabletitle.Bold = false;
    bt3.Title = tabletitle;
    bt3.TableWidth="7in";
    add(chapter,bt3);
    parastr301='The table above shows the first 18 variables for Dust aerosol particles.';
    parastr302=' Column 1 shows he short name for each variable while column 2 provides a brief description of the variable.';
    parastr303=' The structure of the variable is Geo2d means that it is a 2 dimension georeference variable on the standard Merra2 grid.';
    parastr304=' All the variables are plotted will be plotted using the same subroutine,ikind is the tag number used by the plot routine.';
    parastr305=' The final column details whether the variable is a source,or sink for that aerosol species or a chemical process.';
    parastr306=' Dust emissions tend to be correlated with geographic features and prevailing wind.';
    parastr307=' The major effect of dust on the atmosphere is that dust particles serve as seeds for cloud formation.';
    parastr309=strcat(parastr301,parastr302,parastr303,parastr304,parastr305,parastr306,parastr307);
    p31= Paragraph(parastr309);
    p31.Style = {OuterMargin("0pt", "0pt","20pt","10pt")};
    add(chapter,p31);
% Add Table showing Dust Aerosol Variables Pt2
    T4=[VariableTableHdr;VariableTableDustPt2];
    tbl4=Table(T4);
    tbl4.Style = [tbl4.Style {Border('solid','black','3px')}];
    tbl4.TableEntriesHAlign = 'center';
    tbl4.HAlign='center';
    tbl4.ColSep = 'single';
    tbl4.RowSep = 'single';
    r = row(tbl4,1);
    r.Style = [r.Style {Color('red'),Bold(true)}];
    bt4 = BaseTable(tbl4);
    tabletitle = Text('Variable List For Dust Part 2');
    tabletitle.Bold = false;
    bt4.Title = tabletitle;
    bt4.TableWidth="7in";
    add(chapter,bt4);
    parastr401='The table above shows the last 10 variables for Dust aerosol particles.';
    parastr402=' Column 1 shows he short name for each variable while column 2 provides a brief description of the variable.';
    parastr403=' The structure of the variable is Geo2d means that it is a 2 dimension georeference variable on the standard Merra2 grid.';
    parastr404=' All the variables are plotted will be plotted using the same subroutine,ikind is the tag number used by the plot routine.';
    parastr405=' The final column details whether the variable is a source,or sink for that aerosol species or a chemical process.';
    parastr406=' Dust emissions tend to be correlated with geographic features and prevailing wind.';
    parastr407=' The major effect of dust on the atmosphere is that dust particles serve as seeds for cloud formation.';
    parastr409=strcat(parastr401,parastr402,parastr403,parastr404,parastr405,parastr406,parastr407);
    p41= Paragraph(parastr409);
    p41.Style = {OuterMargin("0pt", "0pt","10pt","10pt")};
    add(chapter,p41);
    parastr411='For the GOCART Model,dust areosol particles are grouped into five bins based on size..';
    parastr412=' All partcile diameters are in microns.';
    parastr413=' Bin 001 ranges from 0.10 to 0.18 ,while Bin 002 ranges from 0.18 to .30 .';
    parastr414=' Bin 003 covers the range from 0.30 to 0.60 ,microns and the next larger Bin 004 spans 0.60 to 1.0 microns.';
    parastr415=' The final bin covers partciles in the 1.0 to 1.8 microns.';
    parastr416=' There are three larger bins 06-08 that go all the way out to 10 microns but the diagnostic file does not report these values.';
    parastr419=strcat(parastr411,parastr412,parastr413,parastr414,parastr415,parastr416);
    p42= Paragraph(parastr419);
    p42.Style = {OuterMargin("0pt", "0pt","10pt","10pt")};
    add(chapter,p42);
% Add Table showing Organic Carbon Variables 
    add(chapter,br);
    T5=[VariableTableHdr;VariableTableOC];
    tbl5=Table(T5);
    tbl5.Style = [tbl5.Style {Border('solid','black','3px')}];
    tbl5.TableEntriesHAlign = 'center';
    tbl5.HAlign='center';
    tbl5.ColSep = 'single';
    tbl5.RowSep = 'single';
    r = row(tbl5,1);
    r.Style = [r.Style {Color('red'),Bold(true)}];
    bt5 = BaseTable(tbl5);
    tabletitle = Text('Variable List For Organic Carbon');
    tabletitle.Bold = false;
    bt5.Title = tabletitle;
    bt5.TableWidth="7in";
    add(chapter,bt5);
    parastr501='The table above shows the first 15 variables for Organic Carbon aerosol particles.';
    parastr502=' Column 1 shows he short name for each variable while column 2 provides a brief description of the variable.';
    parastr503=' The structure of the variable is Geo2d means that it is a 2 dimension georeference variable on the standard Merra2 grid.';
    parastr504=' All the variables are plotted will be plotted using the same subroutine,ikind is the tag number used by the plot routine.';
    parastr505=' The final column details whether the variable is a source,or sink for that aerosol species or a chemical process.';
    parastr506=' Organic carbon particles are a subset of carbon aerosols.';
    parastr507=' Black carbon particles mostly absorb solar radiation and thus warm the atmosphere .';
    parastr508=' Organic particles primary affect is to scatter this same radiation.';
    parastr509=strcat(parastr501,parastr502,parastr503,parastr504,parastr505,parastr506,parastr507,parastr508);
    p51= Paragraph(parastr509);
    p51.Style = {OuterMargin("0pt", "0pt","10pt","10pt")};
    add(chapter,p51);
% Add Table showing Sulfate Variables Pt1 
    add(chapter,br);
    T6=[VariableTableHdr;VariableTableSulfatesPt1];
    tbl6=Table(T6);
    tbl6.Style = [tbl6.Style {Border('solid','black','3px')}];
    tbl6.TableEntriesHAlign = 'center';
    tbl6.HAlign='center';
    tbl6.ColSep = 'single';
    tbl6.RowSep = 'single';
    r = row(tbl6,1);
    r.Style = [r.Style {Color('red'),Bold(true)}];
    bt6 = BaseTable(tbl6);
    tabletitle = Text('Variable List Sulfates Pt1');
    tabletitle.Bold = false;
    bt6.Title = tabletitle;
    bt6.TableWidth="7in";
    add(chapter,bt6);
    parastr601='The table above shows the first 18 variables for Sulfate aerosol particles.';
    parastr602=' Column 1 shows he short name for each variable while column 2 provides a brief description of the variable.';
    parastr603=' The structure of the variable is Geo2d means that it is a 2 dimension georeference variable on the standard Merra2 grid.';
    parastr604=' All the variables are plotted will be plotted using the same subroutine,ikind is the tag number used by the plot routine.';
    parastr605=' The final column details whether the variable is a source,or sink for that aerosol species or a chemical process.';
    parastr606=' Sulfate particles mostly reflect solar radiation and thus tend to cool the atmosphere .';
    parastr609=strcat(parastr601,parastr602,parastr603,parastr604,parastr605,parastr606);
    p61= Paragraph(parastr609);
    p61.Style = {OuterMargin("0pt", "0pt","10pt","10pt")};
    add(chapter,p61);
    add(chapter,p51);
% Add Table showing Sulfate Variables Pt2 
    add(chapter,br);
    T7=[VariableTableHdr;VariableTableSulfatesPt2];
    tbl7=Table(T7);
    tbl7.Style = [tbl7.Style {Border('solid','black','3px')}];
    tbl7.TableEntriesHAlign = 'center';
    tbl7.HAlign='center';
    tbl7.ColSep = 'single';
    tbl7.RowSep = 'single';
    r = row(tbl7,1);
    r.Style = [r.Style {Color('red'),Bold(true)}];
    bt7 = BaseTable(tbl7);
    tabletitle = Text('Variable List Sulfates Pt2');
    tabletitle.Bold = false;
    bt7.Title = tabletitle;
    bt7.TableWidth="7in";
    add(chapter,bt7);
    parastr701='The table above shows the last 12 variables for Sulfate aerosol particles.';
    parastr702=' Column 1 shows he short name for each variable while column 2 provides a brief description of the variable.';
    parastr703=' The structure of the variable is Geo2d means that it is a 2 dimension georeference variable on the standard Merra2 grid.';
    parastr704=' All the variables are plotted will be plotted using the same subroutine,ikind is the tag number used by the plot routine.';
    parastr705=' The final column details whether the variable is a source,or sink for that aerosol species or a chemical process.';
    parastr706=' Sulfate particles mostly reflect solar radiation and thus tend to cool the atmosphere .';
    parastr709=strcat(parastr701,parastr702,parastr703,parastr704,parastr705,parastr706);
    p71= Paragraph(parastr709);
    p71.Style = {OuterMargin("0pt", "0pt","10pt","10pt")};
    add(chapter,p71);
    ab=1;
    add(rpt,chapter);
    ab=2;
end

